### ISSUE TITLE
Keyboard is jumping on and off in "Send transaction"  screen in case of changing recipient

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10185]
# Bug Report

## Problem
When enter recipient address or scanning valid QR on "Send transaction"  screen focus for a moment is set on amount field  (so the keyboard is opened, and then it is hidden)

#### Expected behavior
Keyboard is not hidden

#### Actual behavior
Keyboard appears for a moment and hides
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/4557972/77064528-eba05c00-69df-11ea-9148-5ba6d28cb63a.gif)

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status > Wallet
- Tap on Send transaction
- Choose > Scan QR in "Choose recipient"
- Scan valid QR

### Additional Information

- Status version: nightly 19/03/2019
- Operating System: Android, iOS

**Comment by churik** [comment]
same behavior after scanning QR in https://github.com/status-im/status-react/pull/10280 with parameters - keyboard is shown for a moment and then it is closing (IOS)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4557972/79209530-db936500-7e43-11ea-9768-cce87a334204.gif)

**Comment by Ferossgp** [comment]
@churik I think this is already fixed in 1.5?

**Comment by churik** [comment]
@Ferossgp no, still reproducible, but it is a bit faster than before.
