### ISSUE TITLE
Status browser doesn't show full URL

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#10473]
Right now if you open a site with a path, like https://status.im/snt-utility/ what you'll see in the address bar will be just the domain:

![status_app_just_domain](https://user-images.githubusercontent.com/2212681/80698036-2ff04300-8ada-11ea-9a7b-f9f8c97073e9.jpg)

But any normal browser would show the URL without the protocol: `status.im/snt-utility/`

**Comment by andremedeiros** [comment]
Safari on iOS only displays the padlock (open or closed) and the domain name. I think we might want to stay consistent here.

@hesterbruikman WDYT?

**Comment by hesterbruikman** [comment]
Leaving this to the ninja of browser navigation @errorists 

Personally I'm not a frequent iOS user and when I do, I'm confused by the url being obfuscated.

**Comment by errorists** [comment]
yea, don't care much what Safari on iOS does. we should totally try and fit and middle truncate the entire URL 👍

**Comment by hesterbruikman** [comment]
fyi Guideline for url display: https://user-images.githubusercontent.com/61156799/81282968-3479a600-905c-11ea-9961-fd2254c6735b.png

**Comment by cammellos** [comment]
seems like this is resolved, please feel free to reopen if necessary.

**Comment by jakubgs** [comment]
Pretty sure this is still not resolved. Screenshot from the nightly, no path in the URL:
![Screenshot_20200917-225755](https://user-images.githubusercontent.com/2212681/93527600-6586b300-f939-11ea-89c5-f2a8c4410ddf.jpg)
That should be https://dap.ps/discover-dapps/categories/MARKETPLACES.

**Comment by churik** [comment]
still relevant on 1.13

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
