### ISSUE TITLE
Apps crash when connecting to store server?

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-react#13811]
# Bug Report

## Problem 

When I open my app, it crashes/close few seconds after opening.

#### Expected behavior

No crash.

#### Actual behavior

Crashes

### Reproduction

1. Open Status app
2. Use biometric to log in
3. Wait for network logo to go  from red to grey
4.a. The network logo remains grey -> no problem, app does not crash
4.b. the network logo disappears -> app crashes

I have been able to reproduce the 4.a./4.b. behaviour. If the app does not crash I can log in/out to hopefully restart the connection attempt ot a store server.

## Additional Information

- Status version: 1.19.0
- Operating System: Android
- **Using wakuv2.prod fleet**

Not sure how to add logs

**Comment by fryorcraken** [comment]
I confirm no issue when using `eth.prod` (waku v1) fleet. I am guessing this is related to the deployment of nwaku v0.11?

**Comment by qoqobolo** [comment]
Can reproduce this on Nightly without biometric login using **wakuv2.prod** and **wakuv2.test** fleets

Logs: [crashlog_wakuv2fleet.log](https://github.com/status-im/status-mobile/files/9357514/crashlog_wakuv2fleet.log)

https://user-images.githubusercontent.com/67952253/185063299-ed60a0b9-306b-4404-88cf-5c63c05eca0d.mp4

**Comment by cammellos** [comment]
Relevant logs:

```
08-17 09:42:48.261 28420     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
08-17 09:42:48.261 28420     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6f667137b4]
08-17 09:42:48.261 28420     0 E Go      : 
08-17 09:42:48.261 28420     0 E Go      : goroutine 2894 [running]:
08-17 09:42:48.262 28420     0 E Go      : github.com/status-im/status-go/vendor/github.com/status-im/go-waku/waku/v2/protocol/store.(*WakuStore).Query(0x4005cdbe60, {0x6f67ad1448, 0x40036ef1a0}, {{0x40001b6260, 0x1a}, {0x4002dddf80, 0x4, 0x4}, 0x170c11f213834c00, 0x170c120312a6e600}, ...)
08-17 09:42:48.262 28420     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/status-im/go-waku/waku/v2/protocol/store/waku_store.go:623 +0x2d4
08-17 09:42:48.262 28420     0 E Go      : github.com/status-im/status-go/wakuv2.(*Waku).Query(0x4005d31680, {0x4001e1c430, 0x4, 0x4}, 0x62fc9bae, 0x62fc9bf7, {0x4000f3f1c0, 0x3, 0x4})
08-17 09:42:48.262 28420     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:896 +0x1c4
08-17 09:42:48.262 28420     0 E Go      : github.com/status-im/status-go/eth-node/bridge/geth.(*gethWakuV2Wrapper).RequestStoreMessages(0x4000010e30, {0x4006701f80, 0x35, 0x40}, {{0x40036e6620, 0x20, 0x20}, 0x62fc9bae, 0x62fc9bf7, 0x3e8, ...})
08-17 09:42:48.262 28420     0 E Go      : 	github.com/status-im/status-go/eth-node/bridge/geth/wakuv2.go:206 +0x368
08-17 09:42:48.262 28420     0 E Go      : github.com/status-im/status-go/protocol/transport.(*Transport).createMessagesRequestV2(0x40000eba40, {0x4006701f80, 0x35, 0x40}, 0x62fc9bae, 0x62fc9bf7, 0x4002ddde40, {0x4001af6470, 0x4, 0x4})
08-17 09:42:48.262 28420     0 E Go      : 	github.com/status-im/status-go/protocol/transport/transport.go:483 +0xd8
08-17 09:42:48.262 28420     0 E Go      : github.com/status-im/status-go/protocol/transport.(*Transport).SendMessagesRequestForTopics(0x40000eba40, {0x6f67ad1448, 0x40036ef080}, {0x4006701f80, 0x35, 0x40}, 0x62fc9bae, 0x62fc9bf7, {0x0, 0x0, ...}, ...)
08-17 09:42:48.262 28420     0 E Go      : 	github.com/status-im/status-go/protocol/transport/transport.go:501 +0x9c
08-17 09:42:48.262 28420     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).processMailserverBatch.func1(0x40027ae800, {0x4006701f80, 0x35, 0x40}, {0x62fc9bae, 0x62fc9bf7, {0x0, 0x0}, {0x4001af6470, 0x4, ...}, ...}, ...)
08-17 09:42:48.262 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver.go:586 +0xf8
08-17 09:42:48.263 28420     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).processMailserverBatch(0x40027ae800, {0x62fc9bae, 0x62fc9bf7, {0x0, 0x0}, {0x4001af6470, 0x4, 0x4}, {0x4002cb7600, 0x4, ...}})
08-17 09:42:48.263 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver.go:591 +0xa78
08-17 09:42:48.263 28420     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).syncFiltersFrom(0x40027ae800, {0x40000815c0, 0x4, 0x4}, 0x0)
08-17 09:42:48.263 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver.go:457 +0xdb4
08-17 09:42:48.263 28420     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).syncFilters(...)
08-17 09:42:48.263 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver.go:521
08-17 09:42:48.263 28420     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).RequestAllHistoricMessages(0x40027ae800)
08-17 09:42:48.263 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver.go:324 +0x194
08-17 09:42:48.263 28420     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).performMailserverRequest(0x40027ae800, 0x40066f1f38)
08-17 09:42:48.263 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver.go:124 +0x1a8
08-17 09:42:48.263 28420     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).handleMailserverCycleEvent.func1(0x40027ae800)
08-17 09:42:48.263 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:495 +0x44
08-17 09:42:48.263 28420     0 E Go      : created by github.com/status-im/status-go/protocol.(*Messenger).handleMailserverCycleEvent
08-17 09:42:48.263 28420     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:494 +0xf48
08-17 09:42:48.892 28950 28950 E chromium: [0817/094248.891712:ERROR:elf_dynamic_array_reader.h(61)] tag not found
08-17 09:42:48.937 28420 28640 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 28640 (Thread-8), pid 28420 (status.ethereum)
08-17 09:42:49.037 28953 28953 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
08-17 09:42:49.040   923   923 I tombstoned: received crash request for pid 28640
08-17 09:42:49.041 28953 28953 I crash_dump64: performing dump of process 28420 (target tid = 28640)

```

**Comment by richard-ramos** [comment]
Fixed in https://github.com/status-im/status-go/pull/2780

**Comment by Parveshdhull** [comment]
@churik, Should we close this issue?

**Comment by churik** [comment]
Still no, as new status-go version with a fix is still not in status-react. I'm keeping eye on this issue, and will close it once the fix is in status-react.

Thank you for ping @Parveshdhull !

**Comment by churik** [comment]
Issue is not reproducible anymore on nightly 29/08/2022
