### ISSUE TITLE
The textbox is shown as focused after chat is opened as result user can't close it unless starts typing

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14536]
**Steps to reproduce:**
1. Create new 1-1 chat with the contact
2. Go to the contacts
3. Tap on the 'chat' icon of the user
![image](https://user-images.githubusercontent.com/52490791/207583315-d3294b53-2474-4352-85fd-6e17d8d60183.png)
4. Go to the list of chats
5. Open the 1-1 chat

**Actual result:**
- The textbox is shown as focused after chat is opened
- The user can't close it unless some message is sent

https://user-images.githubusercontent.com/52490791/207583532-65ece7e8-f1c4-49d0-aed1-6d42edf67322.mp4
![image](https://user-images.githubusercontent.com/52490791/207583922-8ab4d10c-1236-459d-831f-d9134a4d2625.png)

**Expected result:** 
The input textbox is not focused
![image](https://user-images.githubusercontent.com/52490791/207584051-6fca9a34-d427-4f57-842b-0e67cc8eb146.png)

**ENV:** Samsung Galaxy S20+ v10, Huawei p20 light

**ADDITIONAL INFO:**
This defect is reproducible in 40% of cases. If it is not reproduced at first, then do the following steps:
1. Tap 'back' button in order to be navigated to the chat list
2. Open chat again

**Comment by churik** [comment]
Reproducible on emulators with Android10, that we're using in e2e.
Extremely annoying issue.

**Comment by ibrkhalil** [comment]
Fixed, Kindly check on this PR
https://github.com/status-im/status-mobile/pull/14571

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil . Current issue is still reproduced
**Steps to reproduce:**
1. Open any chat
2. Scroll up
3. Tap 'back' button
4. Reopen the chat again

**Actual result:**

https://user-images.githubusercontent.com/52490791/208401040-cd0d3247-273b-46ba-a41d-9ed5dd42fecb.mp4

**Expected result:**
Textbox is not focused after the chat is opened

**ENV:** Samsung Galaxy S20+ v10, Huawei p20 light

**ADDITIONAL INFO:**
This issue is reproducible in 20% of cases. Try to reopen the chat several times

**Comment by churik** [comment]
Reproduced in 50% of cases on my Android emulator with these params:
![Virtual Device Configuration 2023-01-03 14-46-47](https://user-images.githubusercontent.com/4557972/210369668-70bd9c5e-9bf7-418d-bd7c-5ace6a5d7249.png)

https://user-images.githubusercontent.com/4557972/210369719-a2d20f03-5c5b-4ac9-aa2a-e03bef80b95f.mp4

**Comment by Parveshdhull** [comment]
hi @VladimrLitvinenko, Is the issue still reproducible?

**Comment by VolodLytvynenko** [comment]
hi @Parveshdhull I was not able to reproduce it anymore. Thank you!
