### ISSUE TITLE
Status Mobile Not Working❗

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14592]
Something is wrong with Status mobile app today. Not sure if it is just on `develop` (or is it just me? not sure).

Suddenly all the data on the account I was using is gone, then I tried to reinstall the app and create new account, but the app crashes at new account creation (with error `Login failed: LISTEN UDP 0.0.0.0:9000: BIND: ADDRESS ALREADY IN USER`).

I am facing this issue on both iOS and Android.

**Comment by OmarBasem** [comment]
So after restarting my machine it is back working. But status desktop is not working now with error `Login failed: LISTEN UDP 0.0.0.0:9000: BIND: ADDRESS ALREADY IN USER`. Initially when status-mobile was not working I had that same error and status desktop was running. So now I am not able to run both at the same time for some reason..

**Comment by OmarBasem** [comment]
So actually status-mobile is still not working on latest develop. Not able to create new account or receive any messages.

**Comment by OmarBasem** [comment]
No data is being displayed in the app

![Simulator_Screen_Shot_-_iPhone_14_-_2022-12-21_at_12 23 29](https://user-images.githubusercontent.com/29354102/208840600-40a225c9-6f0a-4360-80e3-5a158766849b.png)
![Simulator_Screen_Shot_-_iPhone_14_-_2022-12-21_at_12 23 33](https://user-images.githubusercontent.com/29354102/208840611-ec3dfda2-5941-4372-8fc8-c9d24d2edc60.png)

**Comment by siddarthkay** [comment]
For me also status-mobile ( not latest develop ) but this branch -> https://github.com/status-im/status-mobile/tree/14588-add-message-delivery-states 
does not work with status-desktop v0.8.0 that we are currently dogfooding.

This seems to be a dogfooding blocker.

However, status-mobile works alone when I terminate status-desktop process
@iurimatias 

<img width="623" alt="Screenshot 2022-12-21 at 12 43 03 PM" src="https://user-images.githubusercontent.com/64726664/208843258-03bbd05d-ffde-41b9-a149-2a8b9913af3e.png">

**Comment by siddarthkay** [comment]
However!
When I terminate the mobile simulator and close down all my terminals ( clojure and metro )
I am able to log into status-desktop..

<img width="905" alt="Screenshot 2022-12-21 at 12 48 24 PM" src="https://user-images.githubusercontent.com/64726664/208844159-5e9f33fe-8226-4b5b-8fb5-ba3026266e8a.png">

<img width="1196" alt="Screenshot 2022-12-21 at 12 49 00 PM" src="https://user-images.githubusercontent.com/64726664/208844258-ef884c48-40b2-4e57-b991-79c5457e6729.png">

**Comment by siddarthkay** [comment]
So the issue is that status-mobile and status-desktop are conflicting somewhere when we run them on the same machine @cammellos @OmarBasem 

One more thing to note is that I started noticing this issue yesterday after switching fleet from "eth.prod" to "status.prod"

**Comment by OmarBasem** [comment]
According to @smohamedjavid that's the latest commit that does not have the issue
![Screenshot_2022-12-21_at_12 42 25_PM](https://user-images.githubusercontent.com/29354102/208844870-1537333c-6616-46b0-93b6-c28093895082.png)

**Comment by OmarBasem** [comment]
> So the issue is that status-mobile and status-desktop are conflicting somewhere when we run them on the same machine @cammellos @OmarBasem
> 
> One more thing to note is that I started noticing this issue yesterday after switching fleet from "eth.prod" to "status.prod"

For me, even when desktop is closed no data is displayed, everything is empty like the above screenshots

**Comment by siddarthkay** [comment]
@OmarBasem : can you confirm which fleet you are connected to?
At the moment status.prod fleet works for me on mobile simulator when desktop app is terminated.

<img width="287" alt="Screenshot 2022-12-21 at 1 00 28 PM" src="https://user-images.githubusercontent.com/64726664/208846205-06b9d229-82a3-46db-af36-0e7c8d3c614b.png">

**Comment by siddarthkay** [comment]
> According to @smohamedjavid that's the latest commit that does not have the issue ![Screenshot_2022-12-21_at_12 42 25_PM](https://user-images.githubusercontent.com/29354102/208844870-1537333c-6616-46b0-93b6-c28093895082.png)

@yqrashawn : does status-desktop and status-mobile work for you together?

**Comment by yqrashawn** [comment]
no, they don't work together, must quit status-desktop @siddarthkay

**Comment by flexsurfer** [comment]
i have similar issue on ios simulator in latest develop, not desktop running, i think we might have two different issues in the same time

**Comment by yqrashawn** [comment]
`[Wed Dec 21 2022 15:44:30.994]  ERROR    ERROR [status-im.utils.fx:36] - Merging fx with common-key:  :status-im2.common.json-rpc.events/call [{:method "wakuext_unreadActivityCenterNotificationsCount", :params [], :on-success #object[Function], :on-error #object[Function]}] [{:method "wakuext_activityCenterNotificationsBy", :params ["" 20 5 2], :on-success #object[Function], :on-error #object[Function]}]`

got an error on relogin, desktop is closed

**Comment by flexsurfer** [comment]
```
[Wed Dec 21 2022 08:45:11.449]  ERROR    ERROR [status-im.chat.models.loading:58] - failed loading messages test {:code -32000, :message "sql: Scan error on column index 18, name \"album_id\": converting NULL to string is unsupported"}
```

whats that ?

**Comment by siddarthkay** [comment]
> ```
> [Wed Dec 21 2022 08:45:11.449]  ERROR    ERROR [status-im.chat.models.loading:58] - failed loading messages test {:code -32000, :message "sql: Scan error on column index 18, name \"album_id\": converting NULL to string is unsupported"}
> ```
> 
> whats that ?

I saw this error yesterday as well right after I sent messages to @cammellos on simulator when my fleet was eth.prod and after I switched to status.prod I saw this error in logs..
However new chats with users worked fine, this issue would always come when I would open @cammellos's chat

<img width="310" alt="Screenshot 2022-12-21 at 1 20 05 PM" src="https://user-images.githubusercontent.com/64726664/208849834-e33ae35b-45e8-4208-8ce3-947223578cb6.png">

Chat with another user (myself on actual device) works fine,( ignore the colors, i'm working on somethin )

<img width="312" alt="Screenshot 2022-12-21 at 1 20 59 PM" src="https://user-images.githubusercontent.com/64726664/208850195-5baab676-2373-4914-850a-7c53ba356157.png">

**Comment by flexsurfer** [comment]
> `[Wed Dec 21 2022 15:44:30.994] ERROR ERROR [status-im.utils.fx:36] - Merging fx with common-key: :status-im2.common.json-rpc.events/call [{:method "wakuext_unreadActivityCenterNotificationsCount", :params [], :on-success #object[Function], :on-error #object[Function]}] [{:method "wakuext_activityCenterNotificationsBy", :params ["" 20 5 2], :on-success #object[Function], :on-error #object[Function]}]`
> 
> got an error on relogin, desktop is closed

did we move json-rpc ?

**Comment by yqrashawn** [comment]
> > `[Wed Dec 21 2022 15:44:30.994] ERROR ERROR [status-im.utils.fx:36] - Merging fx with common-key: :status-im2.common.json-rpc.events/call [{:method "wakuext_unreadActivityCenterNotificationsCount", :params [], :on-success #object[Function], :on-error #object[Function]}] [{:method "wakuext_activityCenterNotificationsBy", :params ["" 20 5 2], :on-success #object[Function], :on-error #object[Function]}]`
> > got an error on relogin, desktop is closed
> 
> did we move json-rpc ?

yes, moved to `status-im2.common.json-rpc.events` maybe should add this to `mergeable-keys`? or revert it?

**Comment by yqrashawn** [comment]
> `[Wed Dec 21 2022 15:44:30.994] ERROR ERROR [status-im.utils.fx:36] - Merging fx with common-key: :status-im2.common.json-rpc.events/call [{:method "wakuext_unreadActivityCenterNotificationsCount", :params [], :on-success #object[Function], :on-error #object[Function]}] [{:method "wakuext_activityCenterNotificationsBy", :params ["" 20 5 2], :on-success #object[Function], :on-error #object[Function]}]`
> 
> got an error on relogin, desktop is closed

fixed with this
<img width="710" alt="image" src="https://user-images.githubusercontent.com/15090582/208851414-96b6d97c-62e9-4fcc-a3ce-5d034305e5f5.png">

will it cause any other issue? there are two json-rpc/call @flexsurfer

**Comment by yqrashawn** [comment]
created a pr https://github.com/status-im/status-mobile/pull/14594 @flexsurfer

**Comment by yqrashawn** [comment]
still conflict with status-desktop

**Comment by flexsurfer** [comment]
yeah as i said we have more than one issue, desktop is different one, most likely related to status-go

**Comment by cammellos** [comment]
> [Wed Dec 21 2022 08:45:11.449]  ERROR    ERROR [status-im.chat.models.loading:58] - failed loading messages test {:code -32000, :message "sql: Scan error on column index 18, name \"album_id\": converting NULL to string is unsupported"}

I believe there's a fix for this in status-go https://github.com/status-im/status-go/commit/b1ff13eb7d9ccaa9beecc4cd3ca0c103a83e3950 , but yes, the issue is that album-id could be empty, so we should either do that or use sql.NulString cc @OmarBasem 

The issue about status-desktop and mobile, is that both try to bind UDP port 9000, that's for discovery, and so they can't run on the same machine (I believe you can use ENV variable on desktop to set the port cc @richard-ramos ), but we should fix this, I don't think there's any reason why we want to run discovery on 9k, we should probably use a random port ideally, if that's possible (i.e pass 0), but I don't believe that's supported.

**Comment by flexsurfer** [comment]
so we have 3 issues
1) minor 
```
ERROR ERROR [status-im.utils.fx:36] - Merging fx with common-key: :status-im2.common.json-rpc.events/call [{:method "wakuext_unreadActivityCenterNotificationsCount", 
```
2) major
```
[Wed Dec 21 2022 08:45:11.449] ERROR ERROR [status-im.chat.models.loading:58] - failed loading messages test {:code -32000, :message "sql: Scan error on column index 18, name "album_id": converting NULL to string is unsupported"}
```
3) major
`The issue about status-desktop and mobile, is that both try to bind UDP port 9000`

**Comment by cammellos** [comment]
> 3. major
>    `The issue about status-desktop and mobile, is that both try to bind UDP port 9000`

For this, if we merge https://github.com/status-im/status-mobile/pull/14575

you should be able to change `UDPPort` to something that does not clash, for the time being, while we make the port dynamic on status-go

**Comment by flexsurfer** [comment]
1 .  https://github.com/status-im/status-mobile/pull/14594
2.  we need to bump status-go and update in mobile develop

**Comment by flexsurfer** [comment]
1. should be fixed now in latest develop, app is not empty anymore

**Comment by rasom** [comment]
@cammellos should we change it to 9001 on `develop` for the time being? I mean in https://github.com/status-im/status-mobile/pull/14575 ?

**Comment by cammellos** [comment]
> @cammellos should we change it to 9001 on `develop` for the time being? I mean in #14575 ?

I think we should let the devs do that, since it's not really a fix, we still have the same issue, and people might be running multiple emulators etc

**Comment by flexsurfer** [comment]
2. https://github.com/status-im/status-mobile/pull/14596

**Comment by flexsurfer** [comment]
2. should be fixed in the latest develop, empty chats are fixed

**Comment by flexsurfer** [comment]
btw i don't have 3 on latest develop and latest desktop master

**Comment by OmarBasem** [comment]
> @OmarBasem : can you confirm which fleet you are connected to? At the moment status.prod fleet works for me on mobile simulator when desktop app is terminated.
> 
> <img alt="Screenshot 2022-12-21 at 1 00 28 PM" width="287" src="https://user-images.githubusercontent.com/64726664/208846205-06b9d229-82a3-46db-af36-0e7c8d3c614b.png">

I was connected to status.prod which did not work. It is now working after switching to eth.prod

**Comment by churik** [comment]
https://github.com/status-im/status-mobile/issues/14592#issue-1505694783 is the same https://github.com/status-im/status-mobile/issues/14467 I believe

**Comment by yqrashawn** [comment]
Seems can be closed?
