### ISSUE TITLE
The logo image is fetched instead of banner image in communities on mobile

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15162]
**Steps to reproduce:**
1. Go to Desktop -> Go to community creation flow
2. Set different images for community logo and for community banner
![image](https://user-images.githubusercontent.com/52490791/220597297-9c58a300-43c1-4d9e-a761-8d5f26cfe233.png)

3. Create current community
4. Invite a mobile user to the community
5. Join the community as a mobile user
6. Open community overview page

**Actual result:**
The logo image is fetched into logo and into banner value
![image](https://user-images.githubusercontent.com/52490791/220598357-ea8f1ff2-0fbd-405e-b61f-cc095945a9e9.png)

**Expected result:**
The logo image is fetched into logo. The banner image fetched into banner value

**ENV:** Nightly [22 Feb 2023]

**Comment by jo-mut** [comment]
@VladimrLitvinenko @Parveshdhull  i think this issue is resolved in this pr #15095 but let me confirm

**Comment by Parveshdhull** [comment]
> @VladimrLitvinenko @Parveshdhull i think this issue is resolved in this pr #15095 but let me confirm

Awesome, Thank you

**Comment by pavloburykh** [comment]
> @VladimrLitvinenko @Parveshdhull i think this issue is resolved in this pr #15095 but let me confirm

@jo-mut @Parveshdhull @VladimrLitvinenko actually it is not fixed. Behaviour slightly changed but it is still not as expected. 

### ISSUE 1 Background image is fetched as logo on Community screen

https://user-images.githubusercontent.com/97245802/223977498-4b0f6ff1-9a82-4814-a3b2-dc08603f952d.mp4


### Question/ISSUE 2 Background image is not fetched for community card within Discover community list

Is it expected or should also been fixed by https://github.com/status-im/status-mobile/pull/15095 ?

![photo_2023-03-09 11 25 18](https://user-images.githubusercontent.com/97245802/223978276-cdc279b7-bd87-44db-9fd2-0c73027e5ee6.jpeg)

**Comment by jo-mut** [comment]
@pavloburykh i may have missed on resolved the conflicts. Let me go through the code on

**Comment by pavloburykh** [comment]
> @pavloburykh i may have missed on resolved the conflicts. Let me go through the code on

@jo-mut sorry, nevermind. ISSUE 1 appeared to be PR bug in https://github.com/status-im/status-mobile/pull/15161 I will log it there. It is okay in nightly.

At the same time ISSUE 2 is reproducible in nightly, so the question "Is it expected or should also been fixed by https://github.com/status-im/status-mobile/pull/15095 ?" is relevant.

**Comment by jo-mut** [comment]
this issue resolved in #15302
