### ISSUE TITLE
Android UI freezes after app reopening and tapping AC icon (see steps and preconditions in the description)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15230]
Follow below steps to reproduce the issue on Android

**Steps:** 

1. Enable notifications background service
2. Open Activity center (AC)
3. Close the app while being located on AC screen
4. Reopen the app
5. Tap on AC icon (bell)
6. Observe the result

**Expected result:** AC screen is opened

**Actual result:** app UI freezes. Unable to navigate through the app. Need to sign out and sign in manually to fix the issue with freezing upon tapping AC icon. 

[Status-debug-logs (14).zip](https://github.com/status-im/status-mobile/files/10871633/Status-debug-logs.14.zip)

https://user-images.githubusercontent.com/97245802/222437287-95d6138c-3d5c-4ab4-b259-b16bf3efc7dc.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
cc @ilmotta

**Comment by flexsurfer** [comment]
related to https://github.com/status-im/status-mobile/pull/15225

**Comment by ilmotta** [comment]
Hey @pavloburykh. I think the best for now is to revert the recently PR I merged. It was supposed to be harmless, but it seems some devices need a higher delay (I reduced it recently). I'll create a PR going back to the full 250ms delay to open the AC.

**Comment by ilmotta** [comment]
> cc @ilmotta

Thanks @flexsurfer. Yes, totally related. I saw this exact same problem, but only with very small delays, like 10ms. It seems a delay of 50ms is not enough, so I'll just go back to the original implementation, it's not worth messing around with this now.

**Comment by ilmotta** [comment]
@flexsurfer, can you please approve the fix I pushed now? https://github.com/status-im/status-mobile/pull/15232 Thank you!

**Comment by pavloburykh** [comment]
> #15232

@ilmotta @flexsurfer  Unfortunately I am still reproducing this UI freeze issue in latest PR build https://github.com/status-im/status-mobile/pull/15216 which I suppose should already include the fix https://github.com/status-im/status-mobile/pull/15232 from develop branch.

**Comment by ilmotta** [comment]
@pavloburykh, do you know if this issue is on `develop`? If it's not then we know the culprit is in https://github.com/status-im/status-mobile/pull/15216

**Comment by pavloburykh** [comment]
> @pavloburykh, do you know if this issue is on `develop`? If it's not then we know the culprit is in #15216

@ilmotta  Let me rebuild builds with latest develop and check. Will provide an update soon.

**Comment by pavloburykh** [comment]
> @pavloburykh, do you know if this issue is on `develop`? If it's not then we know the culprit is in #15216

@ilmotta Reproduced in latest develop. 
**UPDATE** sorry, that was an old develop. Still waiting for the new builds.

**Comment by pavloburykh** [comment]
@ilmotta sorry for confusion)) one more **UPDATE:** the develop build was correct (the latest one). So I confirm that bug is still there.

**Comment by ilmotta** [comment]
>@ilmotta sorry for confusion)) one more UPDATE: the develop build was correct (the latest one). So I confirm that bug is still there.

Thank you @pavloburykh. So this is actually good, because it allows me to fix it in a separate, narrow PR, which is easier for all of us to test and avoid regressions.
