### ISSUE TITLE
[Android] Keyboard is not closed if album selector is opened

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15511]
#### Steps to reproduce:
1. Go to the chat
2. Tap on the input textbox to show the keyboard
3. Tap on the 'album' icon to open the album selector

#### Actual result:
The Album selector is opened and the keyboard is shown as opened too

https://user-images.githubusercontent.com/52490791/228198091-828e51ab-1b38-4590-9216-201a5ca2566f.mp4

#### Expected result:
The keyboard is closed if the album selector is opened

#### ENV:
Nightly [28 Mar 2023]

#### Devices:
- real device: Huawei p20 light, android 9
- emulator: Pixel 3 XL; Android 10

**Comment by ajayesivan** [comment]
Adding `blocked` label since the composer is being re-implemented by @OmarBasem.

**Comment by OmarBasem** [comment]
Fixed in https://github.com/status-im/status-mobile/pull/15639 (for the new composer). This issue can be closed.

**Comment by VolodLytvynenko** [comment]
Hi, @OmarBasem still reproduced in the latest nightly [2 May 2023, 03:08].
Devices:
- real device: Huawei p20 light, Android 9
- android studio: Pixel 6. Android 12

**Comment by OmarBasem** [comment]
@VladimrLitvinenko that's because the new composer is currently disabled on `develop` until it is complete. You can check that latest build of the new composer here: 
Android: https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230501-134354-ba73c0-pr15772-universal.apk
iOS: https://i.diawi.com/jsvPN2

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko that's because the new composer is currently disabled on `develop` until it is complete. You can check that latest build of the new composer here: Android: https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230501-134354-ba73c0-pr15772-universal.apk iOS: https://i.diawi.com/jsvPN2

Got it.Tt works in the latest build of new composer

**Comment by OmarBasem** [comment]
@VladimrLitvinenko I think it working properly now on latest develop

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko I think it working properly now on latest develop

@OmarBasem Yep. It works. Thank you!
