### ISSUE TITLE
Unread counter is located behind AC icon if notification is received while Shell was opened (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16594]
**Preconditions:** User A - Android, User B - any other device

Reproducing on Android 12, Samsung Galaxy A52

**Steps:** 

1. Create a new User A
2. Make User A and User B mutual contacts
3. Create community by User A
4. Share community to User B
5. Open Shell by User A
6. Send community join request by User B to User A
7. Observe the location of AC unread counter for User A

**Actual result:** unread counter is located behind AC. 

<img width="322" alt="Monosnap 2023-07-13 17-23-14" src="https://github.com/status-im/status-mobile/assets/97245802/02e9fb73-9efb-4ed4-a7e1-56604c28c0f0">

https://github.com/status-im/status-mobile/assets/97245802/6bc6c05b-3fe9-4f89-aab4-44c280032b7b

[User_A_logs.zip](https://github.com/status-im/status-mobile/files/12040372/User_A_logs.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
@pavloburykh  I tried to reproduce this but seems to work just fine on my device. I wonder if its  a device specific issue or it has already been resolved in another PR. Could try to reproduce again on your device and see if its still the case when you find some time. 

<img src="https://github.com/status-im/status-mobile/assets/28704507/923f9cfc-96bd-4320-ba15-6d6c44242a97" width="375">

**Comment by pavloburykh** [comment]
> @pavloburykh I tried to reproduce this but seems to work just fine on my device. I wonder if its a device specific issue or it has already been resolved in another PR. Could try to reproduce again on your device and see if its still the case when you find some time.
> 
> <img alt="" width="375" src="https://user-images.githubusercontent.com/28704507/254406688-923f9cfc-96bd-4320-ba15-6d6c44242a97.jpeg">

Hi @jo-mut as far as I know it is not device specific as @churik has also faced it on her Pixel 7a. 
I am still reproducing the bug on my Samsung Galaxy A52, so it is definitely still there.

**Comment by jo-mut** [comment]
I have managed to reproduce it. thanks
