### ISSUE TITLE
 Mention turns into public key when editing a message containing mention

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17929]
Follow-up on https://github.com/status-im/status-mobile/pull/17785
Not reproducible every time, more visible on Android for me

**Steps:** 

1. Open any chat
2. Send a message with a mention
3. Open editing of the message
4. Pay attention to how mention looks like

**Actual result:** mention turns into public key 

https://github.com/status-im/status-mobile/assets/97245802/86ebba10-c179-4a85-a0c4-6e8d2d2ed012

**Expected result:** mention does not turn into pub key

**Comment by clauxx** [comment]
@VolodLytvynenko Can we have another look at this one? I tried it now on both android and ios and couldn't reproduce it at all. Could be that it was fixed together with other composer bugs. Can you have a look?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko Can we have another look at this one? I tried it now on both android and ios and couldn't reproduce it at all. Could be that it was fixed together with other composer bugs. Can you have a look?

@clauxx  Indeed. It seems the issue has been resolved. Thank you!

**Comment by pavloburykh** [comment]
Re-opening this issue as we are still facing it. Unfortunately we do not have clear steps how to reproduce it, so we will update the issue once figure out.

**Comment by qoqobolo** [comment]
@Samyoul I see you added a `low-priority` label to this issue but left it in 2.28, what do you think about moving it to 2.29?
It's hard to reproduce indeed.
