### ISSUE TITLE
Some collectibles images formates are not supported

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18527]
Refer to comment https://github.com/status-im/status-mobile/pull/18404#issuecomment-1889456894

### Actual result:
Collectibles images are not visible. The empty space is shown instead

https://github.com/status-im/status-mobile/assets/52490791/98ff1b13-9f95-4ccc-ab77-d22b66e46081

### Expected result:
Collectibles are visible

### Logs:
[android_logcat4.txt](https://github.com/status-im/status-mobile/files/13919101/android_logcat4.txt)

### Devices:
Android studio: Pixel XL API 33
Real device: Samsung Galaxy A04s, Android 12

### Additional info:
Unfortunately, I cannot provide the user seed phrase. However, I can provide the Ethereum address, which can be added as a watch-only account. Please request this information directly to me if it is needed for debugging

**Comment by mmilad75** [comment]
It's related to https://github.com/status-im/status-mobile/issues/18631

**Comment by ulisesmac** [comment]
@VolodLytvynenko I think this issue has been fixed in:
https://github.com/status-im/status-mobile/pull/18577

Since there are no empty spaces in the collectible listing.

**Comment by pavloburykh** [comment]
> @VolodLytvynenko I think this issue has been fixed in: #18577
> 
> Since there are no empty spaces in the collectible listing.

Hey @ulisesmac! We are still facing empty collectibles, so it is not fixed.

On video below you can see the following: 

1. Some collectibles have empty images. 
2. Some collectibles have 'Missing image' state, despite image is being loaded when opening collectible.

**Comment by qoqobolo** [comment]
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14824448/Status-debug-logs.zip)

https://github.com/status-im/status-mobile/assets/67952253/d316a099-ee4e-4c12-9862-c6bbf4f201e1

**Comment by ulisesmac** [comment]
@mmilad75 I think you are working on this, right? if so, could you please take this issue?

**Comment by J-Son89** [comment]
@VolodLytvynenko - while there is some collectible media types currently unsupported, there is a component which now displays this info. Is this issue still relevant?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko - while there is some collectible media types currently unsupported, there is a component which now displays this info. Is this issue still relevant?

@J-Son89  the issue is not relevant anymore. Can be closed
