### ISSUE TITLE
[Communities] QR-code to share community channel is null 

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18857]
# Bug Report
https://github.com/status-im/status-mobile/pull/18807
## Problem 
[comment]: # (A problem description)

#### Expected behavior
QR-code looks as [designed](https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=2345-300688&mode=design&t=ZZumLRHC4nc4XtcI-0) and contains link to community channel

#### Actual behavior
QR-code to share community channel is null and looks not as designed (size, boarders)
<img width="403" alt="Screenshot 2024-02-16 at 11 37 31" src="https://github.com/status-im/status-mobile/assets/147824399/8dc67c17-e7c5-4011-a675-4c52cd21d58d">

### Reproduction

1. Login to app
2. Go to communities
3. Long tap on any channel OR open any chanel and tap on three dots menu
4. Tap Share QR-code

### Additional Information

- Status version: PR
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mariia-skrypnyk** [comment]
Communication from this [thread](https://discord.com/channels/1103692771585433630/1207974239571808296) will be continued here.

**Comment by J-Son89** [comment]
@yqrashawn this issue is not needed, It's fixed in the initial unmerged pr 👍

**Comment by mariia-skrypnyk** [comment]
Hi!

Issue still exist.

**User scans Community Channel QR code but nothing happens**

**Steps:**
1. User A goes to Communities list -> Opens any community -> Long tap on any channel -> Show QR code
2. User B opens Scan QR screen and scans QR code from User B device

**Actual result:** nothing happened after scanning, User B sees his Community screen

https://github.com/status-im/status-mobile/assets/147824399/8b4ea44f-7479-40d6-8fd6-02fe444402ac


**Expected result:** community channel opened

*Issue is present on both plaforms
** Release build from 28/03

**Comment by alwx** [comment]
@mariia-skrypnyk ok, checking it

**Comment by churik** [comment]
Closed in favour of https://github.com/status-im/status-mobile/issues/18743
