### ISSUE TITLE
Jump to button overlaps Logout button on the Profile screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18893]
# Bug Report

## Problem 
[comment]: # (A problem description)
User still can tap a Logout but need to find a free space on the Logout button for this purpose

#### Expected behavior
Buttons look as designed [here](https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?type=design&node-id=3773-221806&mode=design&t=6VjQ1LSVnDiMyB2y-0)
<img width="270" alt="Screenshot 2024-02-19 at 09 57 11" src="https://github.com/status-im/status-mobile/assets/147824399/29784960-b96f-4d59-8579-211f6cff000e">

#### Actual behavior
<img width="350" alt="Screenshot 2024-02-19 at 09 58 14" src="https://github.com/status-im/status-mobile/assets/147824399/517b8b60-7aae-4899-b8e6-779cf89fed66">

### Reproduction

1. Login to Status app
2. Go to Profile
3. Scroll down to Logout button

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Device: Samsung A34, iPhone SE

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Checking and potentially fixing this one today.

**Comment by alwx** [comment]
Seems like it has already been fixed in the latest build. Can someone from @status-im/mobile-qa confirm?
<img width="564" alt="Screenshot 2024-03-14 at 15 31 18" src="https://github.com/status-im/status-mobile/assets/911127/94b605ea-0ef6-4b82-803e-e4cc44a251cf">

**Comment by qoqobolo** [comment]
Hey @alwx , this is how it looks in today's nightly on my real devices - iPhone SE and Pixel 7a.
The issue is still there. Could you try to check this on a real device, pls? 

<img width="390" alt="Screenshot 2024-03-15 at 10 16 33" src="https://github.com/status-im/status-mobile/assets/67952253/85ef03b3-9db8-4e8e-b1a6-70a603665db6">
<img width="314" alt="Screenshot 2024-03-15 at 10 16 42" src="https://github.com/status-im/status-mobile/assets/67952253/b933481e-315f-4170-a6b3-9adaf2fff9a1">

**Comment by alwx** [comment]
@qoqobolo ok, checking it today
