### ISSUE TITLE
Add the "long-press on token" context drawer on the main wallet screen

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19221]
# Bug Report

## Problem 

Currently, the long-press-on-token context drawer only opens inside a wallet account. 
However, according to the designs, it also should work the same on the main wallet screen. 

#### Expected behavior
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7701-155014&mode=design&t=YonFIdRniXlBn2gQ-4

<img width="1659" alt="Screenshot 2024-03-13 at 11 24 28" src="https://github.com/status-im/status-mobile/assets/67952253/b4bf57fa-0969-4ba3-a7a2-0de1aaadb8b3">

#### Actual behavior

Long-press doesn't work

https://github.com/status-im/status-mobile/assets/67952253/1ccb69fc-84bf-413a-9b06-b6f2501cedbb

### Reproduction

1. Open Wallet
2. Long-tap a token

### Additional Information

- Status version: nightly 13/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ulisesmac** [comment]
This is being addressed in 
- #19515
since that PR adds this missing feature related to our wizard mechanism,

**Comment by J-Son89** [comment]
> This is being addressed in 
> 
> - #19515
> 
> since that PR adds this missing feature related to our wizard mechanism,

We probably need this issue still to hook up buy, bridge and receive. No?

Also the options are different for watch only so we need to handle that too!

**Comment by J-Son89** [comment]
Which btw we have all this functionality, it's just to connect it up!

**Comment by ulisesmac** [comment]
@J-Son89  Ok, then I'll address it separately, since I dont want #19410 to become bigger.

**Comment by ulisesmac** [comment]
@J-Son89 Since you have a PR for the "Receive" action, I think all of these actions are being covered. So we can close this issue, wdyt?

**Comment by J-Son89** [comment]
Yep sounds good @ulisesmac! Wdyt @qoqobolo ?
