### ISSUE TITLE
The app randomly gets stuck on the login page.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19484]
The current issue occurs very rarely, and there are no exact steps on how to reproduce it. I hope the logs might help

### Steps:
1. Go to log in page
2. Attempt to log in using valid password

### Actual result:
The app randomly gets stuck on the login page.

https://github.com/status-im/status-mobile/assets/52490791/e257e0b5-0c25-40ad-8b1f-229e956a20ab

### Expected result:
The user is login

### Logs:
[logs (1).txt](https://github.com/status-im/status-mobile/files/14848252/logs.1.txt)

**Comment by ibrkhalil** [comment]
Might be a relevant line
```
type=1400 audit(0.0:5140): avc:  denied  { bind } for  scontext=u:r:untrusted_app:s0:c62,c259,c512,c768 tcontext=u:r:untrusted_app:s0:c62,c259,c512,c768 tclass=netlink_route_socket permissive=0 bug=b/155595000 app=im.status.ethereum.pr
```

**Comment by ibrkhalil** [comment]
type=1400 errors turned out to be [SELinux](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/troubleshooting-problems-related-to-selinux_using-selinux) related, Investigating

**Comment by ibrkhalil** [comment]
An [issue](https://github.com/tailscale/tailscale/issues/2290#issuecomment-871455637) with SELinux with targetSdkVersions higher than 29?
CC: @siddarthkay

**Comment by ibrkhalil** [comment]
> The current issue occurs very rarely, and there are no exact steps on how to reproduce it. I hope the logs might help
> 
> ### Steps:
> 1. Go to log in page
> 2. Attempt to log in using valid password
> 
> ### Actual result:
> The app randomly gets stuck on the login page.
> 
>  android.mp4 
> ### Expected result:
> The user is login
> 
> ### Logs:
> [logs (1).txt](https://github.com/status-im/status-mobile/files/14848252/logs.1.txt)

May I have some more information about the device tested?

Like Model, Android version and if it was rooted or not

**Comment by VolodLytvynenko** [comment]
> > The current issue occurs very rarely, and there are no exact steps on how to reproduce it. I hope the logs might help
> > ### Steps:
> > 
> > 1. Go to log in page
> > 2. Attempt to log in using valid password
> > 
> > ### Actual result:
> > The app randomly gets stuck on the login page.
> > android.mp4
> > ### Expected result:
> > The user is login
> > ### Logs:
> > [logs (1).txt](https://github.com/status-im/status-mobile/files/14848252/logs.1.txt)
> 
> May I have some more information about the device tested?
> 
> Like Model, Android version and if it was rooted or not

Hey @ibrkhalil 
This issue is reproducible for me on the following models:
-  Pixel 7a, Android 13
- iPhone 11 Pro max, IOS 17

Additionally, it is reproducible on different devices for the QA team

**Comment by ibrkhalil** [comment]
> > > The current issue occurs very rarely, and there are no exact steps on how to reproduce it. I hope the logs might help
> > > ### Steps:
> > > 
> > > 1. Go to log in page
> > > 2. Attempt to log in using valid password
> > > 
> > > ### Actual result:
> > > The app randomly gets stuck on the login page.
> > > android.mp4
> > > ### Expected result:
> > > The user is login
> > > ### Logs:
> > > [logs (1).txt](https://github.com/status-im/status-mobile/files/14848252/logs.1.txt)
> > 
> > 
> > May I have some more information about the device tested?
> > Like Model, Android version and if it was rooted or not
> 
> Hey @ibrkhalil This issue is reproducible for me on the following models:
> 
> * Pixel 7a, Android 13
> * iPhone 11 Pro max, IOS 17
> 
> Additionally, it is reproducible on different devices for the QA team

Logs would be really helpful if possible for these devices.

**Comment by ibrkhalil** [comment]
> An [issue](https://github.com/tailscale/tailscale/issues/2290#issuecomment-871455637) with SELinux with targetSdkVersions higher than 29? CC: @siddarthkay

As @VolodLytvynenko said that the issue happens on iOS then it's highly unlikely to be a SELinux error.

**Comment by seanstrom** [comment]
What do we think about adding a timeout to the login screen? That way if the login native function fails for any reason we'll have a way to unfreeze the screen (and maybe show an error). Thoughts?

**Comment by siddarthkay** [comment]
@VolodLytvynenko : These logs don't have any debug messages. 
Next time you reproduce it could you please ensure your device has set log level to "DEBUG".

You can find this in profile > settings > advanced > log level

<img width="416" alt="Screenshot 2024-04-10 at 8 37 46 PM" src="https://github.com/status-im/status-mobile/assets/64726664/425a52f2-a409-47e3-87c9-b6ca008336e3">

**Comment by siddarthkay** [comment]
Hi @seanstrom @ibrkhalil @VolodLytvynenko : To me it looks like the media server was also not running when the attempt to login was made. Hence we do not see the account's profile picture.
Seems to be that after adding a few accounts an old account may enter a zombie like state.
We'll have to try to reproduce locally to find out why that happens..

**Comment by seanstrom** [comment]
Yeah I agree, we should try debugging what happens on the login screen. I can try seeing what happens if i disable the media server before logging in, that might help confirm what’s happening.

I also tried debugging what happens if the native module function would fail, and it seems that would also freeze the login screen. I think this can happen because when we login we send a request to login, wait for a separate event to be received, and then login the app. If that separate event is never received then we’ll be stuck at the login screen I think.

**Comment by siddarthkay** [comment]
> if i disable the media server before logging in

Ah we need not do that actually. Media server not running could be the symptom that might need fixing and might indicate something that broke right before that stage. If we fix that we may fix this issue.
But yeah its hard to say at this point without a successful reproduction locally.


> it seems that would also freeze the login screen. I think this can happen because when we login we send a request to login, wait for a separate event to be received, and then login the app. If that separate event is never received then we’ll be stuck at the login screen

This part of login could definitely be made more robust like you said.

Regarding the root cause, we could decorate the logout part which starts a media server in status-go with more logs to see if it malfunctions -> https://github.com/status-im/status-go/blob/e2a4a2289618910a062b8d51105acb58449180bc/api/geth_backend.go#L2202-L2239

**Comment by qfrank** [comment]
my guess, might be relate to this https://github.com/waku-org/go-waku/pull/1085 , if logout stuck, login will stuck

**Comment by VolodLytvynenko** [comment]
hey. @ibrkhalil @siddarthkay apologies for initially providing only 'info' level logs. Although this issue doesn't occur frequently, I just encountered it again with 'debug' log level. hope these logs might help to catch what going on

### Device:
Pixel 7a, Android 14

### Logs:
[Status-debug-logs (7).zip](https://github.com/status-im/status-mobile/files/14959969/Status-debug-logs.7.zip)

**Comment by qfrank** [comment]
my previous guess seems proberbly right since i can't see "status node stopped" in geth.log for the second logging out🤪.

**Comment by seanstrom** [comment]
Nice! 🙌
Just curious, is it possible to send a restart command to status-go if we’re in a deadlock situation? Or are we forced to quit the app because of the deadlock?

**Comment by qfrank** [comment]
> is it possible to send a restart command to status-go if we’re in a deadlock situation

it's possible to send a restart command, however, the deadlock will still be there.

I think we can improve the usage of lock in status-go side, e.g. add timeout for holding a lock and report possible deadlock? cc @cammellos

**Comment by cammellos** [comment]
@qfrank was this fixed by your two commits?

**Comment by qfrank** [comment]
I think so, but not sure if @VolodLytvynenko still faced this issue after these 2 commits. @cammellos 

> @qfrank was this fixed by your two commits?

**Comment by qfrank** [comment]
I left the opportunity to @VolodLytvynenko to close this issue. 🙂

**Comment by VolodLytvynenko** [comment]
> I left the opportunity to @VolodLytvynenko to close this issue. 🙂

@cammellos @qfrank I haven't encountered this issue anymore. I will reopen it if it still reproduces. For now, let's close it.
