### ISSUE TITLE
White line on Contacts tab appears when tab has a badge on it

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20084]
# Bug Report

### Reproduction

1. Login to app as User A
2. Send friend request to User B
3. As User B look at your Contacts tab on Messages screen

#### Expected behavior
https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1786-389868&t=LrlWroTfHEYJn3SF-0

<img width="262" alt="Screenshot 2024-05-17 at 13 16 13" src="https://github.com/status-im/status-mobile/assets/147824399/65949f11-cb0b-48a2-84fb-fc587e2cd9d9">

#### Actual behavior
<img width="270" alt="Screenshot 2024-05-17 at 13 14 42" src="https://github.com/status-im/status-mobile/assets/147824399/652c71a0-8460-4455-b7cb-c245650bc65e">

### Additional Information

- Status version: nightly 17/05
- Operating System: Android
- Device Samsung A34 (14.0)

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment]
I have not reproduced this android (samsung s22 android 14.0)

**Comment by jo-mut** [comment]
It looks as if one of the view has a border, When I investigated it I did not see the issue.  I dont think its device specific, it appears to me that this issue is already fixed

**Comment by mariia-skrypnyk** [comment]
@jo-mut hi!

Thanks, I'll recheck and let you know!

**Comment by mariia-skrypnyk** [comment]
> It looks as if one of the view has a border, When I investigated it I did not see the issue. I dont think its device specific, it appears to me that this issue is already fixed

@jo-mut I've checked on today's nightly and issue still exist.

Please, try to reproduce with this step:

- Send friend request to User B
- As User B look at your Contacts tab on Messages screen

Issue reproduces on such devices:
Samsung A34 (14.0)
Samsung A52 (12.0)

**Comment by jo-mut** [comment]
I will check this again

**Comment by jo-mut** [comment]
Android emulator Samsung Galaxy A35 5G (Android 14) & Pixel 6 (Android 13) 

<img src="https://github.com/status-im/status-mobile/assets/28704507/060586b9-0202-497e-9448-92e5f4a2d2b1" width="325">
<img src="https://github.com/status-im/status-mobile/assets/28704507/727b4ca7-32f0-4e58-9f80-01cf04335760" width="325">

I also have not seen the issue on Galaxy s22 (Android 14) real device. I do have the devices on which this is being reproduced. Looks like its device specific.

It could be reproducible on android real devices and not the emulator

**Comment by ilmotta** [comment]
@mariia-skrypnyk @jo-mut, this is a known problem first identified here https://github.com/status-im/status-mobile/pull/14883#issuecomment-1408179486. As you can see in the issue there I attempted a few solutions, but ultimately it's not a bug in our code (necessarily).

We decided in that issue (see this comment https://github.com/status-im/status-mobile/pull/14883#issuecomment-1409209094) that because most models don't show this line artifact we would live with that little bug. This problem happens because tabs with indicators are actually two separate pieces glued together. The right piece is an SVG and has a cutout to simulate a border around the dot indicator.

When that was developed, the AC background had blur, so we could not use a solid border to create a fake illusion of a cutout on the top-right corner of the tab because that looked bad. But on Android we now use a solid color on the AC, so we can fake the cutout with a simple solid color matching the AC background. Same technique for the home tabs.

Back in the days when I developed that, we were much more focused on absolute pixel perfection. Thankfully, that's past. I think nowadays it's not worth dedicating time to this issue given other problems we have. But if we do come back to this, I recommend we apply the fix with a fake cutout on Android and remove the SVG workaround. On iOS there's blur on the AC, so the SVG workaround is actually necessary.

**Comment by jo-mut** [comment]
@ilmotta thanks for this detailed description of the issue. I tried my best with all the devices in my disposable and several samsung emulators and I was unable to reproduce the issue. Make sense not to spend a lot of time on this issue since it does not affect all phones. Its looks ugly I agree but i think its the right call for now. It's a good note for when there is time to work on it and

**Comment by ilmotta** [comment]
Exactly @jo-mut 👍🏼 and thanks for taking a look. I've seen this problem recently in on of my Android devices. It doesn't always happen, it's like sorcery. The good news is that, because we removed blur on Android, we have a proper & quick fix in case we want to attack this issue.

Thank you @mariia-skrypnyk for reporting this problem.
