### ISSUE TITLE
"Error-status-proxy-0.error: execution reverted" error is shown after attempt to approve SNT amount that exceeding previous approval

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21424]
### Preconditions:
Current User has:
- 15500 SNT
- 0.21 ETH

### Steps:
1. Select L1 network.
2. Enter 13,500 SNT to swap to ETH.
3. Approve the transaction (approval is successful https://etherscan.io/tx/0x8c5a4450b2a7eed54a9376b0848b88b41854d5df893923688197d3fa68ac6bf7).
4. Enter a higher amount of SNT (e.g., between 13,501 and 15,000 SNT).

### Actual Result:
The swap transaction fails, and the error message "Error-status-proxy-0.error: execution reverted" is displayed if user enters a value for approval that exceeding previous approved value

Moblie:
![Image](https://github.com/user-attachments/assets/28e50127-5eb1-4137-8812-c47fc5174598)

Desktop
![Image](https://github.com/user-attachments/assets/ef9f1c68-19f1-4a9b-ba03-94f295137fdd)

### Expected Result:
The swap transaction should build successfully without errors, and the swap should proceed smoothly.

### OS: 
IOS, Android, Desktop

### Logs
Mobile [Status-debug-logs (2).zip](https://github.com/user-attachments/files/17344448/Status-debug-logs.2.zip)
Desktop [desktop swap (1).txt](https://github.com/user-attachments/files/17344435/desktop.swap.1.txt)

**Comment by saledjenic** [comment]
@VolodLytvynenko a reason for this issue is Grove in Swap. So this is not an issue in swap logic or so, we just need to remove Grove as an option.

**Comment by shivekkhurana** [comment]
If it's a Grove issue, then shouldn't this PR fix it already: https://github.com/status-im/status-go/pull/5904 ?

**Comment by alwx** [comment]
Could you re-check it? It should've been fixed by the status-go PR.

**Comment by VolodLytvynenko** [comment]
> If it's a Grove issue, then shouldn't this PR fix it already: [status-im/status-go#5904](https://github.com/status-im/status-go/pull/5904) ?

Hi @alwx still reproducible in the scope of [this](https://github.com/status-im/status-mobile/pull/21445) PR both on mobile and desktop

**Comment by alwx** [comment]
@VolodLytvynenko ok, checking it right now but it still seems to be a status-go issue :(

**Comment by saledjenic** [comment]
@VolodLytvynenko I've done some tests and figured out that call `eth_EstimateGas` to estimate approval tx to SNT contract https://etherscan.io/address/0x744d70fdbe2ba4cf95131626614a1763df805b9e for a higher value than one already set return `execution reverted` error, while that's not the case for other contracts, tested with https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.

That's not the case when you're setting approval for the first time (if it was 0 before that).

Why it's like that I have no idea, except that's something up to our SNT contract.

In the video below you can see how it looks (for both contracts, USDC and SNT, I have some amount already approved, when no approvals works fine for SNT contract as well):

https://github.com/user-attachments/assets/8f62978d-c2db-46b1-a8b9-8abb82c04568

**Comment by jrainville** [comment]
@saledjenic SNT is a MineMe contract, which has a couple more features than a normal ERC20 token. That's probably why. It makes most transactions cost a little more.

I'm not sure what we can do to fix it though. It's not like we can update the contract.

**Comment by churik** [comment]
Thank you @saledjenic

**Comment by shivekkhurana** [comment]
I'm moving this to 2.32. 

I also have a thought about how this issue is happening. The error occurs when we try to `approve` twice. Could it be that we need to call `increaseAllowance` the second time ?

**Comment by churik** [comment]
@shivekkhurana I suggest to remove this issue from milestone, as it is clearly contract issue.
The only thing we can do on our side is to set unlimited approval, like other wallets do instead of concrete value.

Please, add this back if you consider this important

**Comment by shivekkhurana** [comment]
We have checked the possible solutions:
- Bundle approve and send as one: not possible on paraswap
- Max approval: possible but frowned upon, this should be the way to test
- integrating Revoke cash.

**Comment by churik** [comment]
cross-linking: https://github.com/status-im/status-mobile/issues/21632

**Comment by churik** [comment]
@shivekkhurana If we’re not planning to work on this right now (no revoking feature or any other changes at the moment), let’s leave a comment here and exclude it from the milestone.  

Let me know what you think!
