### ISSUE TITLE
Multicollectible amount is not updated after transaction until relogin

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21483]
**Steps:** 

1. Send multicollectible from Account A to internal Account B
2. See if collectible amount has been updated after pull to refresh

**Actual result:** amount is not updated until relogin
[Status-debug-logs - 2024-10-22T175917.000.zip](https://github.com/user-attachments/files/17478377/Status-debug-logs.-.2024-10-22T175917.000.zip)

https://github.com/user-attachments/assets/7723c96b-cc43-44b2-8475-b1c12ade2668

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by mohsen-ghafouri** [comment]
Hey @pavloburykh, could you please advice if it's reproducible on desktop as well or not? as i checked the logs it seems status-go send us current count and not the new count.

**Comment by pavloburykh** [comment]
> Hey [@pavloburykh](https://github.com/pavloburykh), could you please advice if it's reproducible on desktop as well or not? as i checked the logs it seems status-go send us current count and not the new count.

Hey @mohsen-ghafouri! You are right. I have just checked Desktop and reproduced the issue.

**Comment by mohsen-ghafouri** [comment]
Thanks @pavloburykh, i will check status-go logic.

**Comment by smohamedjavid** [comment]
> Hey @smohamedjavid, would you mind also check and advice about this issue?https://github.com/status-im/status-mobile/issues/21483
when i was testing i notice that :wallet/collectibles-data-updated recieved wrong balance (current balance and not updated data), I also tried to fetch manually after update but that didn't work too, so IMO the only way to fix it in status-go side. wdyt?
>
> also my draft PR https://github.com/status-im/status-mobile/pull/21867 (not working properly yet)

Based on the changes in the PR #21867, the fetch type is `:fetch-if-cache-old` which is validated against the cache age we set in the params

https://github.com/status-im/status-mobile/blob/5007dc757f3fcd6b5fcc9a54bc532f59a6bd5e80/src/status_im/contexts/wallet/collectible/events.cljs#L28

The cache is valid for 1 hour (bit high) which is why we still see the cached balance. Maybe, we could try `:always-fetch`.

Either way, the RPC will trigger the fetching in async but the response will always return the cached ones. The response will have an map `ownershipStatus` which will contain the state of updating for each chain along with timestamp.

https://github.com/status-im/status-mobile/blob/5007dc757f3fcd6b5fcc9a54bc532f59a6bd5e80/src/status_im/contexts/wallet/collectible/events.cljs#L237-L240

We can try update the above condition to remove the timestamp check (it was added as additional check if the collectible was an account is never fetched - during account recovery). This will update the app-db with updating addresses fetch the collectibles once it's done. I'm thinking this may introduce a loading collectibles UI bug. Need to verify.

Anyways, the client will receive `wallet-collectibles-ownership-update-finished` signal once the update is finished and we fetch the collectibles for that address again.

https://github.com/status-im/status-mobile/blob/5007dc757f3fcd6b5fcc9a54bc532f59a6bd5e80/src/status_im/contexts/wallet/collectible/events.cljs#L172-L183

**Comment by smohamedjavid** [comment]
On the other hand for simplest solution, there are few other RPC which I noticed in the status-go such as `wallet_fetchBalancesByOwnerAndContractAddress`, it might help to get the balance of the collectible. I haven't tried that yet. We can just update the balance in the app-db instead of fetching the whole collectibles data and processing it. WDYT?

If none of the above solution works, we definitely need to check status-go 😅 .

**Comment by mohsen-ghafouri** [comment]
Thank @smohamedjavid for your feedback, I tested once with `:always-fetch` and it didn't help, i will give it another try. also will check `wallet_fetchBalancesByOwnerAndContractAddress` if that can help, I agree that fetching whole collectible is not a good way to handle it and also update the balance in the app-db will save us some api call.  I will try it.

**Comment by mohsen-ghafouri** [comment]
JFYI @smohamedjavid I just tested `wallet_fetchBalancesByOwnerAndContractAddress` it has issue as it send balance of all contract addresses, despite i sent owner address and specific contract address. it seem for now either it should be fixed in status-go side, or fetch all collectible of one account (this also doesn't work well IMO). will discuss about it with you on Monday.

**Comment by VolodLytvynenko** [comment]
hi @mohsen-ghafouri unfortunately the issue still exists in the latest develop after merging [this](https://github.com/status-im/status-mobile/pull/21867) PR.  The multi collectibles amount not updated for the sender after sending is performed (only relogin helps). Could you take a look, please?

https://github.com/user-attachments/assets/10039ffc-2069-4b75-a494-84fa7fe443e7

Logs: https://drive.google.com/file/d/19cOBSdVP_NKQL5A9F-Ykbck4yaeU4cVa/view?usp=drive_link

**Comment by mohsen-ghafouri** [comment]
Hi @VolodLytvynenko, sorry for the delay. I noticed that on the main network, the ownership change event (from status-go) is flaky, sometimes delayed or not received at all. Could you confirm if this issue occurs only on the main network or also on testnet?

**Comment by VolodLytvynenko** [comment]
> Hi [@VolodLytvynenko](https://github.com/VolodLytvynenko), sorry for the delay. I noticed that on the main network, the ownership change event (from status-go) is flaky, sometimes delayed or not received at all. Could you confirm if this issue occurs only on the main network or also on testnet?

@mohsen-ghafouri  This also happens on the testnet, but only after sending collectibles.

For swap, send, and bridge flows, this issue does not occur. Both the sender’s and receiver’s balances update correctly after a pull-to-refresh.

Here are logs of the sent collectible which does not disappear after sending and pull to refresh

https://github.com/user-attachments/assets/ad54f92b-7f39-4ecc-afef-95519e7ea69f

### Logs:
https://drive.google.com/file/d/1IHg2fUEhrEz1BTw6oX4wn7K2eBmy-CkD/view?usp=drive_link

**Comment by mohsen-ghafouri** [comment]
Thanks @VolodLytvynenko, i will investigate more about it.
