### ISSUE TITLE
The max fee estimation on mobile is not matched to the fee on Desktop for bridge transactions

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21620]
### Steps:
1. Go to the bridge page
2. Build the following bridge routes

### Actual result:
Bridge routes are estimated incorrectly

example: 
L2 arb -> L2 opt
or 
L2 arb -> L2 opt

Max fee is estimated as <0.01 USD

![Image](https://github.com/user-attachments/assets/db2f143c-b7f7-4c4b-a3d4-09da9c2751a1)

### Expected result:
The bridge estimation should be matched to the Desktop
![Image](https://github.com/user-attachments/assets/e3be8350-4761-46cf-94f7-b475a4764fa7)

### Additional info:
It seems mobile is not including the "bridge fee" and "approval fee" as desktop does ![Image](https://github.com/user-attachments/assets/efce1fab-d90e-46c5-97da-56f4d478fe82)
![Image](https://github.com/user-attachments/assets/b5a0a044-07b4-45d0-9835-eda2f2c28a93)

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 13 Now

**Comment by alwx** [comment]
Should be fixed by this: https://github.com/status-im/status-mobile/pull/21541

**Comment by VolodLytvynenko** [comment]
issue is not fixed within https://github.com/status-im/status-mobile/pull/21541. Fee estimation still incorrect

**Comment by alwx** [comment]
@VolodLytvynenko Ok, you're right because the fee estimation is still done separately and might be done differently on desktop. Will take a further look at it but for now it's not an issue that's linked to #21541

**Comment by shivekkhurana** [comment]
Moving this to 2.33 as it's not a blocker.

**Comment by churik** [comment]
@alwx hello! what is the progress on this one? 

It would be nice to align with desktop on this one in the upcoming release
 cc @shivekkhurana

**Comment by alwx** [comment]
@churik it's still in progress and partially blocked because I work on it in combination with https://github.com/status-im/status-mobile/issues/21954 which seems very related.
Will update with more details later today and will try to come up with some sort of intermediary solution.

**Comment by churik** [comment]
@VolodLytvynenko is it still relevant?

**Comment by VolodLytvynenko** [comment]
> [@VolodLytvynenko](https://github.com/VolodLytvynenko) is it still relevant?

@alwx @churik still relevant
