### ISSUE TITLE
Swap transaction fails with "No transactions being built" error after successful approval

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21761]
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully my assiumption is correct and this happens because of slippage occurs, the logs will help

You can find recent update in the [comment](https://github.com/status-im/status-mobile/issues/21761#issuecomment-2674011538)

### Steps:

1. Generate swap transaction that **REQUIRES APPROVAL**
2. Approve swap
3. Perform swap

### Actual result:

1. Swap transaction fails with error toast "no transaction been build"
2. For some reason 2 approvals appear in blockchain instead of 1

https://github.com/user-attachments/assets/e2207268-72e2-49e2-beda-b46759686d5b

### Expected result:
No error is shown

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/18021802/Status-debug-logs.zip)

### ENV:
Nightly 5, 2024

**Comment by alwx** [comment]
Currently investigating how it's done on desktop to make our logic match it.

**Comment by anastasiyaig** [comment]
@alwx is there any hidden trick in rounding maybe?
i wonder if there is anything suspicious in
```
2024-12-05T10:37:04.222Z    DEBUG    RequestLogger    call    {"method": "callPrivateRPC", "duration": "4.213745ms", "request": [{"id":1,"jsonrpc":"2.0","method":"wallet_getSuggestedRoutesAsync","params":[{"addrFrom":"0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5","addrTo":"0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5","amountIn":"0x3e8","amountOut":"0x0","disabledFromChainIDs":[1,42161],"disabledToChainIDs":[1,42161],"fromLockedAmount":{},"gasFeeMode":1,"sendType":8,"toTokenID":"ETH","tokenID":"WBTC","uuid":"d1347f73-f5f7-4597-9a44-d406d93e0cfc"}]}], "response": {"id":1,"jsonrpc":"2.0","result":null}}
```
in particular, `"amountOut":"0x0"` and returning `null` as response

i noticed that error mentioned in ticket, is returned by this [function](https://github.com/status-im/status-go/blob/develop/services/wallet/transfer/transaction_manager_route.go#L312), i wonder in which circumstances len is 0

i remember we tweaked rounding in desktop client some time ago https://github.com/status-im/status-desktop/pull/16843/files#diff-b1211fe55c926fb3e8806fad95a9c46175f05adf5e375b6d3ee128b2269f2788

however that may be a red herring

**Comment by churik** [comment]
@alwx any luck on this one?

**Comment by alwx** [comment]
@churik I think this issue is fixed already — at least I cannot reproduce it anymore:

<img width="565" alt="Image" src="https://github.com/user-attachments/assets/61e63c39-cd1d-428a-b2fd-2a884574e5a9" />

**Comment by alwx** [comment]
Could someone from the @status-im/mobile-qa re-check?

**Comment by churik** [comment]
As it was not 100% reproducible, rather when market moved (slippage occured) we cannot reproduce it as well. it does not mean that the bug was fixed unfortunately

**Comment by VolodLytvynenko** [comment]
@alwx Still reproducible. Especially it is often reproducible on the Base chain. 
### Steps:
1. Perform swap 
2. Perfrom swap one more time but using some another asset

### Actual result:

https://github.com/user-attachments/assets/445771ac-b581-4722-b715-0f1f2a9606ad

### ENV:
Nightly 29 jan, 2025

### Logs:
https://drive.google.com/file/d/1tXsGwGRtN2k5kbKgJf07K7EMu-Zz4ZaO/view?usp=drive_link

**Comment by VolodLytvynenko** [comment]
this issue happens even when slippage is not set up

**Comment by pavloburykh** [comment]
@shivekkhurana @alwx @churik @VolodLytvynenko I consider this is quite serious issue and it is still easily reproducible. I think we need to prioritise it ASAP. 

What you can see on the video Below: 

1. Generate swap transaction that **REQUIRES APPROVAL**. In my case it is Tether USD to ETH on Optimism
2. Approve swap
3. Perform swap

**Actual result:** 

1. Swap transaction fails with error toast "no transaction been build"
2. For some reason 2 approvals appear in blockchain instead of 1

<img width="1455" alt="Image" src="https://github.com/user-attachments/assets/61b78ea6-324a-4d15-b7b2-0aa3962fd894" />

- Approval 1 https://optimistic.etherscan.io/tx/0xd3439143fefc37a0cacc0809188f6c4875956c01c7c6f1fc2c2443a8208b8b3f
- Unexpected Approval 2 after sending swap transaction https://optimistic.etherscan.io/tx/0xc470f48867009cc3a05013270cb7028d4615f8bca24f63eb15445a63e2def926

[Status-debug-logs (5).zip](https://github.com/user-attachments/files/18904034/Status-debug-logs.5.zip)

https://github.com/user-attachments/assets/984876bb-7163-4335-8e20-d45f00d59b47

**Comment by pavloburykh** [comment]
### UPDATE:

Looks like the issue is fixed by https://github.com/status-im/status-mobile/pull/22115 

We will double check during release testing and close it if so. 

cc @alwx

**Comment by shivekkhurana** [comment]
Thanks @pavloburykh. This has been on the TODO list since you raised it a few weeks ago. Please leave a comment here if it's fixed ))

**Comment by pavloburykh** [comment]
I am not able to reproduce anymore after https://github.com/status-im/status-mobile/pull/22115 has been merged. Closing this issue.
