### ISSUE TITLE
No dot/comma is shown on keyboard when requesting/sending funds

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2681]
### Description
_Type_: Bug

_Summary_: No dot/comma displayed on keyboard, so can't request or send decimal amount

#### Expected behavior
![image](https://user-images.githubusercontent.com/28752642/33829738-85ec82fc-de82-11e7-929e-b1e760624928.png)

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/33829851-f2942e0a-de82-11e7-8d44-c6a2d689cc34.png)

### Reproduction

* Open Status
* Go to Wallet
* Click Request
* Observe keyboard shown

### Additional Information

* Status version: 0.9.10-433-g25ec3602+ (1990)
* Operating System: Android

#### Logs
TF: https://app.testfairy.com/projects/4803622-status/builds/7246163/sessions/4/?accessToken=XMMInuMJvGuHON--jIcXYCQ56uc

**Comment by yenda** [comment]
Reminder for me : https://github.com/facebook/react-native/issues/12988

**Comment by yenda** [comment]
Fixed in the branch

**Comment by asemiankevich** [comment]
Fixed in branch `0.9.10-438-g6948dd17+`

**Comment by yenda** [comment]
@asemiankevich can you list the devices that encounter this issue as well as the language in which it happens, this is important for this issue. For a device on which the bug is present please try with english US and french or russian

**Comment by yenda** [comment]
@asemiankevich is it still happening ?

**Comment by asemiankevich** [comment]
@yenda yes, it was in place some time ago (couple of weeks) , however i do not own the device now so cant say for sure. @yevh-berdnyk Zhenya, could you please check it?

**Comment by denis-sharypin** [comment]
@yenda  Maybe if we specify a `KeyboardType` to `Numeric` it will work properly?
<img width="776" alt="screenshot 2018-04-17 16 30 06" src="https://user-images.githubusercontent.com/6559881/38876409-b1a33466-425c-11e8-8683-12f2078defe3.png">

**Comment by Serhy** [comment]
I can confirm the issue is still present on Samsung Galaxy Note 4 (with Android 6.0.1).
Tried with English (us), English (uk), French, Russian as @yenda suggested - in all cases, there is no delimiter button on Wallet screen for numeric keyboard:
![screenshot_2018-04-17-17-13-04](https://user-images.githubusercontent.com/8749671/38877835-362770d4-4268-11e8-99c9-0dab8ba1e0f5.png)

**Comment by yevh-berdnyk** [comment]
LG V20, Android 7.0 - without delimiter
![2018-04-17 18 07 11](https://user-images.githubusercontent.com/29711298/38878737-5552bc78-426a-11e8-9817-82db4e1616fc.jpg)

**Comment by Roger--Han** [comment]
we fix this issue by adding inline js autocapitalize="off" to the input field, `<input type="number" autocapitalize="off">`, if this still cannot help you have to set the type to "tel" and only allow user to type 1234567890 and .

**Comment by Serhy** [comment]
I've noticed one thing: in Dapp (Oasis Direct) on the affected device (Galaxy Note 4) numeric fields request numeric keyboard with a dot as separator.
So in Wallet it (still) looks like:
![screenshot_2018-04-17-17-13-04](https://user-images.githubusercontent.com/8749671/38877835-362770d4-4268-11e8-99c9-0dab8ba1e0f5.png)

And this is the same device and OS but in Oasis Direct:

![screenshot_2018-06-18-17-44-49](https://user-images.githubusercontent.com/8749671/41543384-6619a220-731f-11e8-98da-548eacdf1bf0.png)


@goranjovic what's the diference between two: requesting numeric keyboard in numeric field in Wallet (e.g. Send -> Specify amount) and numberic keyboard requested from Dapp (Oasis Direct)?

**Comment by mandrigin** [comment]
@goranjovic @asemiankevich maybe we can make a bounty out of this bug instead?

**Comment by phillbaker** [comment]
It seems like this should have been solved with `decimal-pad` support on android: facebook/react-native#19714, however, I was not able to get `decimal-pad` to work on a physical LG Stylo 3 (Android 7.0) - there was no difference between decimal-pad and numeric.

However, `phone-pad` does give access to a decimal, so that seems like a decent workaround.

**Comment by AnnuRArya** [comment]
Anyone fixed the issue on Samsung ? I have set to Editext in Xamarin.Android
```
android:inputType="numberDecimal"
android:capitalize="none"
`````
and in Dutch the keyboard still shows '.' and no ','

**Comment by churik** [comment]
@Serhy would you mind to recheck it when you have time?
I can't start app on Android 6 in BrowserStack, it is crashed

**Comment by Serhy** [comment]
Yes, it's still present in Release 1.0.1 build:

<img width="354" alt="Screenshot 2020-02-26 at 17 30 02" src="https://user-images.githubusercontent.com/8749671/75359970-cecfa780-58bd-11ea-8b05-d19c182e9e7b.png">

**Comment by richard-ramos** [comment]
@churik, @Serhy 
Is this still an issue? Currently that input field is set as "numeric" as seen on this line https://github.com/status-im/status-react/blob/37028c62a2433067122be126db1183ec4addc487/src/status_im/ui/screens/wallet/send/views.cljs#L104 which according to this guide https://lefkowitz.me/visual-guide-to-react-native-textinput-keyboardtype-options/ should display the keyboard 

On my phone and simulator it displays the dot/comma
![Screenshot_20200420-162531_Status](https://user-images.githubusercontent.com/1106587/79797512-603f2100-8325-11ea-9f70-536d6282442e.jpg)
![Screenshot from 2020-04-20 16-22-38](https://user-images.githubusercontent.com/1106587/79797515-60d7b780-8325-11ea-8841-fd95c33c0414.png)

**Comment by Serhy** [comment]
@richard-ramos yes, it's still an issue (same like in on real https://github.com/status-im/status-react/issues/2681#issuecomment-591486481) 
I see it on real device Samsung Galaxy Note 4 with Android 6.0.1

Here is the video of numeric keyboard view in Status and in Chrome(used Airswap dapp):
https://drive.google.com/file/d/1X1e7-JR7TT9mWqoNqVhWDwA6WZt5kSr6/view?usp=sharing

Here is [keyboard_galaxy_note_4_in_status.txt](https://github.com/status-im/status-react/files/4508410/keyboard_galaxy_note_4-2.txt) for when I tap `Send` button in Status (so keyboard without delimeter appears) and logs [keyboard_galaxy_note_4_chrome-brows.txt](https://github.com/status-im/status-react/files/4508448/keyboard_galaxy_note_4_Chrome-2.txt) for when I tap in input of Dapp to call numeric keyboard
