### ISSUE TITLE
Error Message.from-clock-value must be of type 'number' when sign transaction later from deleted 1-1 chat

### ISSUE THREAD

**Issue by Marina-Kovalevich** [status-im/status-react#3624]
### Description

*Type*: Bug

*Summary*: Error message “message.from-clock-value must be of type ‘number’,got ‘null’ (null)” when sign transaction later if 1-1 chat with this transactions was deleted. After transactions signed user cannot start 1-1 chat with receiver, but is redirected to Unknown chat.

#### Expected behavior
Transaction signed later from wallet, no error appears, user can start 1-1 chat with receiver

#### Actual behavior
If user choose to sign transaction later and delete 1-1 chat, this transaction still can be signed from wallet transaction history, but error appears and when start new 1-1 chat with the receiver user is redirected to unknown chat.

### Reproduction
- Open Status
- Start 1-1 chat (Jarrad)
- Use send transaction command
- Choose sign transaction later
- Delete chat with Jarrad
- Sign transaction from wallet (error appears, transaction signed)
- Start new 1-1 chat with Jarrad

![screenshot_2018-03-19-20-46-08-502_im status ethereum](https://user-images.githubusercontent.com/36479997/37618032-d6dcd974-2bc5-11e8-9099-9e6f4f62685e.png)
![screenshot_2018-03-19-20-53-45-986_im status ethereum](https://user-images.githubusercontent.com/36479997/37618036-de351d8a-2bc5-11e8-8a4b-11861a4e7ab9.png)

### Additional Information

* Status version: Nightly build 19/03/2018

* Operating System: Android

**Comment by asemiankevich** [comment]
i can reproduce on ios as well , the app hangs after the error received on iPhone 7. 
TF for logs https://app.testfairy.com/projects/4803590-status/builds/7906391/sessions/63/?accessToken=tCTL300Kcx1zUwuAxXyILgBtZkQ

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/7906391/sessions/63/?accessToken=tCTL300Kcx1zUwuAxXyILgBtZkQ">TestFairy: Status 0.9.11d779 (2336) @63</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
will be fixed in scope of https://github.com/status-im/ideas/issues/87

**Comment by janherich** [comment]
@asemiankevich could you please check if this is already fixed in develop ? When yes, please close the issue.

**Comment by asemiankevich** [comment]
this issue is still in place @janherich but the error message is different now : `NAME: "Error"
MESSAGE: chat.chat-id must be of type 'string', got 'null' (null)` 
https://app.testfairy.com/projects/4803590-status/builds/8129920/sessions/2/?accessToken=QAQdbWxE-YWV7JKraFOPVq7xTC8

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8129920/sessions/2/?accessToken=QAQdbWxE-YWV7JKraFOPVq7xTC8">TestFairy: Status 0.9.16 (2447) @2</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@janherich I can have a look at it if you don't mind, I was poking around that part of the codebase
