### ISSUE TITLE
Offline messages not received until message sender sends one more message 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3778]
***Type***: Bug

***Summary***: Offline inbox messages does not arrive after contact appears online (even staying >10 minutes). However, please see the details in reproduction ***when*** offline messages arrive:

#### Expected behavior
Offline messages received after contact appears online
#### Actual behavior
Offline messages are not received after contact appears online

### Reproduction

- Install fresh develop build on Device 1 and Device 2
- Create Contact1 and Contact2 respectively
- Both contacts are online and exchanged a text messages
- Contact2 enables airplane mode on device
- Contact1 sends 10 text messages to Contact2
- Contact2 disables airplane mode and stays on Home/1-1chat screen. (you can even stay up to 10 minutes here). 
**Actual result:** no messages received by Contact2

- Contact2 navigates to 1-1 chat screen and sends a text message to Contact1
**Actual result:** Message received by Contact1 as expected

- Contact1 sends one more text message to Contact2
**Actual result:** The very last text message received by Contact2. Also there are 10 messages appeared as 'Waiting for the message to arrive...'. Contact2 can stay for a while (checked 10+ minutes) - but all the messages keep staying in 'Waiting for the message to arrive...' state.

- Contact2 re-logins and navigates to 1-1 chat with Contact1
**Actual result:** No messages that were sent while he was offline at all.

### Additional Information
* Status version: Develop 0.9.10-846-ge9af024e (with merged new-protocol changes)
* Operating System: Android and iOS

### Additional Information
If Contact2 closed the app instead airplane mode - PN received for messages sent to him fine. 

#### Logs

TF logs for the Contact2 who was offline starting from "get back online" step above: https://app.testfairy.com/projects/4803622-status/builds/8048398/sessions/6/?accessToken=LYoAjoVIPtC3Ru1MAGDq-xrouIM

From the logs:
```00:50 I/ReactNativeJS: INFO [status-im.transport.inbox:148] - offline inbox: fetch-peers response [{:id "03f3661686d30509d621dbe5ee2e3082923f25e94fd41a2dd8dd34bb12a0c4e8fbde52247c6c55e86dc209a8e7c4a5ae56058c65f7b01734d3ab73818b44e2a3", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["les/1" "les/2" "shh/6"], :network {:localAddress "192.168.2.63:35517", :remoteAddress "188.166.33.47:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}} {:id "dffef3874011709b12d1e540d83ddb19a9db8614ad9151d05bcf813585e45cbebba5aaea223fe315786c401d8cecb1ad2de9f179680c536ea30311fb21fa934b", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["les/1" "les/2" "shh/6"], :network {:localAddress "192.168.2.63:37027", :remoteAddress "188.166.100.178:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}}]
00:50 I/ReactNativeJS: INFO [status-im.transport.inbox:154] - Peer enode://fa63a6cc730468c5456eab365b2a7a68a166845423c8c9acc363e5f8c4699ff6d954e7ec58f13ae49568600cff9899561b54f6fc2b9923136cd7104911f31cce@163.172.168.202:30303 is not registered. Retrying fetch peers.
00:55 D/ReactNativeJS: DEBUG [status-im.utils.handlers:35] - Handling re-frame event:  :status-im.transport.inbox/fetch-peers
00:55 D/ReactNativeJS: DEBUG [status-im.utils.handlers:35] - Handling re-frame event:  :status-im.transport.inbox/check-peer-added
00:55 I/ReactNativeJS: INFO [status-im.transport.inbox:148] - offline inbox: fetch-peers response [{:id "03f3661686d30509d621dbe5ee2e3082923f25e94fd41a2dd8dd34bb12a0c4e8fbde52247c6c55e86dc209a8e7c4a5ae56058c65f7b01734d3ab73818b44e2a3", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["les/1" "les/2" "shh/6"], :network {:localAddress "192.168.2.63:35517", :remoteAddress "188.166.33.47:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}} {:id "dffef3874011709b12d1e540d83ddb19a9db8614ad9151d05bcf813585e45cbebba5aaea223fe315786c401d8cecb1ad2de9f179680c536ea30311fb21fa934b", :name "StatusIM/v0.9.9-unstable/linux-amd64/go1.9.3", :caps ["les/1" "les/2" "shh/6"], :network {:localAddress "192.168.2.63:37027", :remoteAddress "188.166.100.178:30303", :inbound false, :trusted false, :static true}, :protocols {:shh "unknown"}}]
00:55 I/ReactNativeJS: INFO [status-im.transport.inbox:154] - Peer enode://fa63a6cc730468c5456eab365b2a7a68a166845423c8c9acc363e5f8c4699ff6d954e7ec58f13ae49568600cff9899561b54f6fc2b9923136cd7104911f31cce@163.172.168.202:30303 is not registered. Retrying fetch peers.
00:55 E/ReactNativeJS: ERROR [status-im.transport.inbox:157] - Could not connect to mailserver
00:55 E/unknown:ReactNative: console.error: "ERROR [status-im.transport.inbox:157] - Could not connect to mailserver", stack:
00:55 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$3@12:347932
00:55 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:347729
00:55 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:353001
00:55 E/unknown:ReactNative: c@12:5305735
00:55 E/unknown:ReactNative: r@12:5305917
00:55 E/unknown:ReactNative: <unknown>@12:3240146
00:55 E/unknown:ReactNative: <unknown>@12:3259481
00:55 E/unknown:ReactNative: cljs$core$IKVReduce$_kv_reduce$arity$3@12:545631
00:55 E/unknown:ReactNative: _kv_reduce@12:158196
00:55 E/unknown:ReactNative: reduce_kv@12:268208
00:55 E/unknown:ReactNative: cljs$core$IFn$_invoke$arity$10@12:3256787
00:55 E/unknown:ReactNative: <unknown>@12:5811908
00:55 E/unknown:ReactNative: <unknown>@12:3950298
00:55 E/unknown:ReactNative: invoke_interceptor_fn@12:3878235
00:55 E/unknown:ReactNative: invoke_interceptors@12:3878536
00:55 E/unknown:ReactNative: execute@12:3880233
00:55 E/unknown:ReactNative: handle@12:3889958
00:55 E/unknown:ReactNative: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@12:3924691
00:55 E/unknown:ReactNative: re_frame$router$IEventQueue$_run_queue$arity$1@12:3905427
00:55 E/unknown:ReactNative: <unknown>@12:3911179
00:55 E/unknown:ReactNative: re_frame$router$IEventQueue$_fsm_trigger$arity$3@12:3915390
00:55 E/unknown:ReactNative: <unknown>@12:3907945
00:55 E/unknown:ReactNative: <unknown>@32:1369
00:55 E/unknown:ReactNative: x@32:643
00:55 E/unknown:ReactNative: callTimers@32:2788
00:55 E/unknown:ReactNative: value@27:3582
00:55 E/unknown:ReactNative: <unknown>@27:1067
00:55 E/unknown:ReactNative: value@27:3009
00:55 E/unknown:ReactNative: value@27:1039
03:14 D/ViewRootImpl@ac693ee[MainActivity]: ViewPostImeInputStage processPointer 0
```

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8048398/sessions/6/?accessToken=LYoAjoVIPtC3Ru1MAGDq-xrouIM">TestFairy: Status 0.9.10-846-ge9af024e+ (2403) @6</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
fixed by https://github.com/status-im/status-react/pull/3836

**Comment by Serhy** [comment]
Offline inboxing is not fixed completely. 

Apparently, because app fails to connect to mailservers (```00:55 E/unknown:ReactNative: console.error: "ERROR [status-im.transport.inbox:157] - Could not connect to mailserver",```) which is still the case - offline inboxed messages do not arrive at an account. 

This is described separately in https://github.com/status-im/status-react/issues/3853. 
Let's close current issue.
