### ISSUE TITLE
Apply design for new menu and screens for desktop "+" button

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4434]
### User Story

As a user, I want to see a list of selected topics and be able to add the new topic in one screen.

### Description

*Type*: Feature

*Summary*: public chat in mobile app allows users to see selected channels for quick joining and possibility to create the new channel if there is no useful in list. Users will expect something similar in Desktop as well.
Separate windows should be added for "New Chat" screen and for "Join a public chat" screen

#### Expected behavior
separate screens for "Start new Chat" (described in #4281) and "Join to public chat."
In mobile:
![pub_l](https://user-images.githubusercontent.com/4557972/40484999-f6823b2e-5f65-11e8-945c-4961e3056088.png)

#### Actual behavior
![new](https://user-images.githubusercontent.com/4557972/42505006-23c2d5f8-8446-11e8-8f73-d52c03efb612.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Log in
- Click on +

### Solution

- Menu with new chat options >> zpl.io/bLwR9WJ
<img width="253" alt="captura de pantalla 2018-09-14 a la s 1 52 20 p m" src="https://user-images.githubusercontent.com/37297779/45548662-6bff6300-b825-11e8-99f3-259b1614575e.png">

- New 1:1 chat screen >> Starts here zpl.io/a7ynPBE (navigate left & right on Zeplin to see diff cases)
<img width="488" alt="captura de pantalla 2018-09-14 a la s 1 52 37 p m" src="https://user-images.githubusercontent.com/37297779/45548677-7ae61580-b825-11e8-9cc3-e2bbe416e854.png">

- New public chat screen >> Starts here zpl.io/aBE71Xe  (navigate left & right on Zeplin to see diff cases)
<img width="519" alt="captura de pantalla 2018-09-14 a la s 1 53 13 p m" src="https://user-images.githubusercontent.com/37297779/45548692-8cc7b880-b825-11e8-8ed7-0be205e722ee.png">

**Comment by EugeOrtiz** [comment]
Designs for this can be found here  (Zeplin):
- zpl.io/aBE71Xe
- zpl.io/aBElz8L

**Comment by churik** [comment]
@EugeOrtiz all public chats in the list should be clickable and change color on hover;
Can you please display it on screen as well?

**Comment by EugeOrtiz** [comment]
Yes, here: zpl.io/a3vp03x

**Comment by churik** [comment]
Blocked by https://github.com/status-im/react-native-desktop/issues/256

**Comment by vkjr** [comment]
https://github.com/status-im/react-native-desktop/issues/256 fixed now, so this probably can be unblocked.

**Comment by EugeOrtiz** [comment]
@churik I can still see this issue in the latest build. Is it really done?

**Comment by churik** [comment]
@EugeOrtiz It is not done, it is unblocked for future development by fixing RN-related error.

**Comment by EugeOrtiz** [comment]
This is creating a bigger UX issue. The more I use the app, the more contacts on the list I have and the public chat area gets pushed down and disappears at the bottom:

<img width="1029" alt="captura de pantalla 2018-09-13 a la s 10 15 26 a m" src="https://user-images.githubusercontent.com/37297779/45476171-95918f00-b73e-11e8-9d0b-5c35153c4a54.png">

@chadyj @churik I think we should move this to the TO-DO list soon.

**Comment by chadyj** [comment]
@EugeOrtiz I lost track of the different Zeplin versions. What is the fix for this issue?

**Comment by EugeOrtiz** [comment]
There is only one Zepplin project for desktop >> zpl.io/aXGDvmE

Specifics about this issue:
- Menu with new chat options >> zpl.io/bLwR9WJ
<img width="253" alt="captura de pantalla 2018-09-14 a la s 1 52 20 p m" src="https://user-images.githubusercontent.com/37297779/45548662-6bff6300-b825-11e8-99f3-259b1614575e.png">

- New 1:1 chat screen >> Starts here zpl.io/a7ynPBE (navigate left & right on Zeplin to see diff cases)
<img width="488" alt="captura de pantalla 2018-09-14 a la s 1 52 37 p m" src="https://user-images.githubusercontent.com/37297779/45548677-7ae61580-b825-11e8-9cc3-e2bbe416e854.png">

- New public chat screen >> Starts here zpl.io/aBE71Xe  (navigate left & right on Zeplin to see diff cases)
<img width="519" alt="captura de pantalla 2018-09-14 a la s 1 53 13 p m" src="https://user-images.githubusercontent.com/37297779/45548692-8cc7b880-b825-11e8-8ed7-0be205e722ee.png">

**Comment by chadyj** [comment]
Done in https://github.com/status-im/status-react/pull/6974

**Comment by churik** [comment]
It is not done actually - I changed title to `Apply design`, because the feature is currently implemented without design.
All designs are attached to this issue.
So I'll reopen it if you don't mind

**Comment by EugeOrtiz** [comment]
Moved designs to Figma:
- [Create new 1:1 chat](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=421%3A48)
- [Create new group chat ](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=230%3A11231)
- [Join public chat](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=421%3A3467)
