### ISSUE TITLE
No results displayed in Etheroll

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5162]
### User Story

As a user, I want to see results in Etheroll. 

### Description

*Type*: Bug

*Summary*: On the [Etheroll results page](https://etheroll.com/#/results), I should see a populated list under "All results." 

On Status, it displays 0. 

#### Expected behavior
Etheroll results page displays 100+ results.

<img src="https://user-images.githubusercontent.com/15470435/42677166-da166cd8-8672-11e8-9ede-21808c22544f.PNG" width=250 />

#### Actual behavior
Etheroll results page displays 0 results.

<img src="https://user-images.githubusercontent.com/15470435/42677175-e0aa87be-8672-11e8-88a5-1de9352c9eb3.PNG" width=250/>

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Go to https://etheroll.com in Status
- Click 3 dot menu button 
- Open Results page

<blockquote><div><strong><a href="https://etheroll.com/">Etheroll :: Ethereum casino :: Ether gambling</a></strong></div><div>Provably fair, de-centralized Ethereum casino - gamble online using Ether on the Ethereum network - smart-contract gambling. House edge only 1%.</div></blockquote>

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/42868665-8e68b540-8a7b-11e8-8b69-6cf05c322ebb.png)

**Comment by flexsurfer** [comment]
@mandrigin could you take a look, do we need to implement this on go side?

**Comment by jeluard** [comment]
This issue is blocked by https://github.com/status-im/status-go/issues/1110

**Comment by flexsurfer** [comment]
fixed in develop

**Comment by Serhy** [comment]
Develop build and status-go 'node 0.17.8-beta' : looks good on iOS 12.0.1, Android 6.0.1, Android 7, Android 8! I do see the list results in ehtheroll.com 

Closing this issue.

**Comment by ghost** [comment]
> Develop build and status-go 'node 0.17.8-beta' : looks good on iOS 12.0.1, Android 6.0.1, Android 7, Android 8! I do see the list results in ehtheroll.com
> 
> Closing this issue.

Has this been pushed live? I'm still not seeing results. iOS v12.1.2/Status v0.9.32.

**Comment by rachelhamlin** [comment]
@jimeejones it's not in the release build yet—it should be live in a few weeks.

**Comment by llorehte** [comment]
@rachelhamlin @Serhy Pplease re-open this issue. The original issue is now occurring again, the fix was working for a while, but it looks like the issue has been rasied again. No results show, whereas the results show on desktop with Metamask and also in Coinbase app.

**Comment by flexsurfer** [comment]
it seems this dapp doesn't connect to status provider, in the logs i see 
```
[Error] Could not connect to the server.
[Error] Fetch API cannot load https://localhost:8545/ due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (localhost, line 0)
```
