### ISSUE TITLE
`Type error: re-matches must match against a string.` at attempt to open #status channel

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6087]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: after opening #status public channel got an error

#### Expected behavior
no error

#### Actual behavior
<img width="137" alt="err" src="https://user-images.githubusercontent.com/4557972/46340690-dc3c2000-c63e-11e8-88a6-0a22e7bc48c3.png">

```
00:20 4/Status: 2018-10-02 14:24:55.482 [error][tid:com.facebook.react.JavaScript] TypeError: re-matches must match against a string.
This error is located at:
    in n
    in t
    in RCTView
    in n
    in t
    in t
    in n
    in RCTView
    in t
    in RCTView
    in t
    in t
    in RCTView
    in t
    in n
    in n
    in r
    in n
    in t
    in t
    in n
    in n
    in reagent2
    in root
    in reagent1
    in RCTView
    in RCTView
    in t
```

### Reproduction

- Open Status
- Join `#status`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 02/10/2018
* Operating System: Androi, iOS
* TF session: https://app.testfairy.com/projects/4803590-status/builds/8612915/sessions/4402872233/?accessToken=3jQpkcR6hlk5UoNcguWRQ0FSbNg
In desktop I can see only two empty messages, error isn't shown
<img width="361" alt="1s" src="https://user-images.githubusercontent.com/4557972/46340852-51a7f080-c63f-11e8-94e5-bb9add6e37c3.png">

**Comment by yenda** [comment]
This is already fixed in https://github.com/status-im/status-react/pull/6064 can you check in today nightly (03/10/2018) ?

**Comment by churik** [comment]
@yenda 

Error is still displayed in last [nightly](https://status-im.ams3.digitaloceanspaces.com/StatusIm-181003-025918-0caab1-nightly.apk)

* Prerequisites:
have installed nightly 02/10/2018 with #status chat (so can replicate issue)

* Steps:
1) update to nightly 03/10/2018
2) log in
3) open #status chat

* Expected result:
history is preserved for yesterday and today, no errror is shown

* Actual result:
error is still displayed

* TF session: https://app.testfairy.com/projects/4803622-status/builds/8614367/sessions/4402960561/?accessToken=HKulGjH09Dt9BrnHqnYh2L5MjWg

**Comment by yenda** [comment]
@churik I expected that you would still have the error if you have the messages already in DB please check #6100
