### ISSUE TITLE
No prompt for users what files should be included to crash report

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6656]
### Description

*Type*: Bug
*Summary*: in order to analyze crash logs `cmd` and `.dmp` files are required, but automatically only `.dmp` file is copied, and it is not obvious for user that he need to attach `cmd` as well.
Basically, all or almost all crash reports are unusable.

#### Expected behavior
2 files are copied and attached to the issue

#### Actual behavior
1 file is copied (`.dmp`)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- got a crash
- click Report
- create issue with default text and files
- open [crash repo](https://github.com/status-im/status-react-desktop-reports/)
- check your issue (issue example https://github.com/status-im/status-react-desktop-reports/issues/43)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 08/11/2018
[comment]: # (Android or iOS.)
* Operating System: Mac OSx, Linux

**Comment by churik** [comment]
@MaxRis can you look?

**Comment by maxhora** [comment]
@churik I have found that reportApp Window is not get launched at all if crash happens for non-bundle builds. The fix is available in https://github.com/status-im/status-react/pull/6975
Could you please verify that the described issue with missed files is not reproducible in above mentioned PR (I was not able to repro it locally)? The sources in PR are temporary modified to generate crash on app's start early stage. Thanks

**Comment by SlizkovaGanna** [comment]
@MaxRis  The fix for https://github.com/status-im/status-react/pull/6975 does not solve the issue, since it fixes the reportApp window appearance.
The issue currently is that:
**1)** no files are auto-attached to the report, only what user will choose to attach
**2)** it's not obvious what user should attach even when they want to: the page simply says "Please attach log files"

<img width="357" alt="image" src="https://user-images.githubusercontent.com/43638377/49378224-b9002080-f714-11e8-8951-d9fe7e26a2b2.png">

I would suggest we update the caption to mention specific extensions that should be attached.
**3)** CMD file is not auto-detected in the log files directory, so the user would have no idea where to even get it from, and manually search for it
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/43638377/49378071-6a528680-f714-11e8-8ff7-8b2b6bdd81cb.png">

**Comment by maxhora** [comment]
@SlizkovaGanna @churik sorry, I've missed the point that Issue asks to attach files automatically to the Google Form. I don't see easy way to attach files into Google Form automatically. How about adjusting message in reportApp to ask to attach exactly both files (crash.dmp and Status)? That should minimize the issue.

**Comment by churik** [comment]
@MaxRis  agree, let's do it.

**Comment by churik** [comment]
@MaxRis I guess it shouldn't be time-consuming to implement?
All that required for now - to make explicit prompt that crash.dmp and Status exec both should be attached.
I added it to release 0.9.0 because I believe it is quite important to get these crash logs.

**Comment by maxhora** [comment]
@churik thanks, yes, I will add prompts into available https://github.com/status-im/status-react/pull/6975
