### ISSUE TITLE
Polish Kyber wallet extension

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7219]
Using this issue to track changes required to polish the Kyber wallet extension, so that it meets the standards of a Status native feature.

### UI Issues

- Menu option should be title case: `Exchange Assets` not `assets`
- Screen is cut off at top. Top is white. I should see OS icons on purple BG (iPhone XS): 
<img src="https://user-images.githubusercontent.com/15470435/50826584-5665fa00-133c-11e9-85f9-605dd7be0297.png" width=200/>

- Bad alignment in token selector. Display should be responsive, keeping token symbol on same line as "available":

```
OMGToken
OMG available:
0.063....
```

Instead I see: 
<img src="https://user-images.githubusercontent.com/15470435/50827216-2f102c80-133e-11e9-8d6b-11eefee3de66.png" width=200/>

- Amount field is not responsive to my input. No done/return option, I need to manually click into the next field to move on:
<img src="https://user-images.githubusercontent.com/15470435/50827694-79de7400-133f-11e9-8bb9-e2dfd8ea9f4c.png" width=200/>

### Bugs

- UI frozen after second token selected. I can not complete my exchange from here:
<img src="https://user-images.githubusercontent.com/15470435/50827846-e8233680-133f-11e9-9565-d120c1e3ec64.png" width=250/>

- Attempting to install the extension on one device, I get the following error: 
<img src="https://user-images.githubusercontent.com/15470435/50827042-b4471180-133d-11e9-9276-4901d3b80acf.png" width=250/>

### Additional Information
Tested on nightly using an iPhone XS Max and an iPhone 6s +

**Comment by jeluard** [comment]
# UI issues

- [x] Menu option should be title case: `Exchange Assets` not `assets`
- [x] Screen is cut off at top. Top is white
- [x] Bad alignment in token selector. Display should be responsive, keeping token symbol on same line as "available"
 - Blocked by [Pluto #113](https://github.com/status-im/pluto/issues/113)

# Bugs

- [x] Amount field is not responsive to my input. No done/return option, I need to manually click into the next field to move on
-  Not clear this can be solved
- [x] UI frozen after second token selected. I can not complete my exchange
 - :+1: 
- [x] Attempting to install the extension on one device, I get the following error
 - This is temporary IPFS issue. We could improve the error message

**Comment by jeluard** [comment]
Current Kyber extension: https://status-im.github.io/pluto/try.html?hash=QmaMARUtPrvDmU4RUBaQ4UahVfCeKzGShFGgLZYWanRptN

<blockquote><img src="/pluto/img/favicon.png" width="48" align="right"><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by flexsurfer** [comment]
# UI issues

- [x] Screen is cut off at top. Top is white
https://github.com/status-im/status-react/pull/7251
# Bugs

- [x] Amount field is not responsive to my input. No done/return option, I need to manually click into the next field to move on
-  Amount field in the wallet works the same, there is no return button on a numeric keyboard, but I made some improvements to UI, now all fields should be visible and it's possible to scroll UI and press any control https://github.com/status-im/status-react/pull/7257


Updated extension: https://status-im.github.io/pluto/try.html?hash=QmVe4JFe15BUhELhnUTLegcWF72W9LobgrURDgkL6Dp84h

**Comment by rachelhamlin** [comment]
Reminder for myself - I need to test again once I can complete an exchange (was blocked when I created the issue)

**Comment by jeluard** [comment]
@rachelhamlin All listed issues should be fixed in the following extension version: https://status-im.github.io/pluto/try.html?hash=QmPzBb1siNHz8MtsMXHz7gq92KRTbHW3VHbCJGEiPYvrVr

<blockquote><img src="/pluto/img/favicon.png" width="48" align="right"><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by rachelhamlin** [comment]
Hmm @jeluard, I'm still getting the `unknown-component-property` error on this one.

<img src="https://user-images.githubusercontent.com/15470435/51598120-176ba300-1efd-11e9-8ec6-bd4b215bb985.png" width=200 />

**Comment by rachelhamlin** [comment]
Working beautifully with new nightly!

**Comment by jeluard** [comment]
Updated extension to reflect latest nightly changes: https://status-im.github.io/pluto/try.html?hash=QmeqDrXwwwesgb6Dj9UurtgX1VoS4h6tApxLTLU1BSD7Vo

<blockquote><img src="/pluto/img/favicon.png" width="48" align="right"><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>
